begin;
select plan(8);
create temp table calendar_fixture as select gen_random_uuid() u,gen_random_uuid() w,gen_random_uuid() s,gen_random_uuid() r;
insert into auth.users(id) select u from calendar_fixture;
insert into public.workspaces(id,owner_user_id) select w,u from calendar_fixture;
insert into public.students(id,workspace_id,name) select s,w,'Calendar fixture' from calendar_fixture;
insert into public.schedule_rules(id,workspace_id,student_id,weekdays,time) select r,w,s,array[1],time '18:00' from calendar_fixture;
select private.generate_visits(w,s,'2024-02') from calendar_fixture;
select is((select count(*)::integer from public.visits where student_id=(select s from calendar_fixture)),4,'four Mondays in leap February');
update public.visits set status='absent' where student_id=(select s from calendar_fixture) and date='2024-02-05';
select private.generate_visits(w,s,'2024-02') from calendar_fixture;
select is((select count(*)::integer from public.visits where student_id=(select s from calendar_fixture)),4,'regeneration is idempotent');
select is((select status from public.visits where student_id=(select s from calendar_fixture) and date='2024-02-05'),'absent','regeneration preserves absence');
update public.schedule_rules set weekdays=array[1,2,3,4,5,6,7] where id=(select r from calendar_fixture);
select private.generate_visits(w,s,'2024-02') from calendar_fixture;
select private.generate_visits(w,s,'2025-02') from calendar_fixture;
select private.generate_visits(w,s,'2026-12') from calendar_fixture;
select private.generate_visits(w,s,'2027-01') from calendar_fixture;
select is((select count(*)::integer from public.visits where student_id=(select s from calendar_fixture) and date between '2024-02-01' and '2024-02-29'),29,'leap February ends at 29');
select is((select count(*)::integer from public.visits where student_id=(select s from calendar_fixture) and date between '2025-02-01' and '2025-02-28'),28,'ordinary February ends at 28');
select is((select count(*)::integer from public.visits where student_id=(select s from calendar_fixture) and date between '2026-12-01' and '2026-12-31'),31,'December includes day 31');
select is((select count(*)::integer from public.visits where student_id=(select s from calendar_fixture) and date between '2027-01-01' and '2027-01-31'),31,'new year starts a distinct month');
select is((select count(*)::integer from public.visits where student_id=(select s from calendar_fixture) and date='2027-01-01'),1,'first day of year occurs exactly once');
select * from finish();
rollback;
