/* Estados explícitos de rutina, plantilla global y vista visual de progreso. */
function saveViewContext(){try{sessionStorage.setItem('pulso-view-v5',JSON.stringify({personId:person().id,archiveId:state.archiveId,templateId:state.templateId,draftMode:state.draftMode,week:state.week,day:state.day,document:state.document}))}catch{}}
try{const v=JSON.parse(sessionStorage.getItem('pulso-view-v5')||'null');if(v){const i=DB.people.findIndex(p=>p.id===v.personId);if(i>=0){state.person=i;state.archiveId=person().archives.some(r=>r.id===v.archiveId)?v.archiveId:null;state.templateId=DB.templates.some(r=>r.id===v.templateId)?v.templateId:null;state.draftMode=Boolean(v.draftMode&&person().draft);state.week=Math.min(4,Math.max(1,v.week||1));state.day=Math.max(0,v.day||0);state.document=v.document==='progress'?'progress':'routine'}}}catch{}
function clearRoutineContext(){state.archiveId=null;state.templateId=null;state.draftMode=false;state.day=0}
function routineStatus(){return state.templateId?'Plantilla del banco':state.archiveId?'Rutina anterior':state.draftMode?'Borrador':'Rutina actual'}
function navigation(){
  const items=[['agenda','calendar','Agenda'],['students','users','Alumnos'],['bank','routine','Banco de rutinas'],['exercises','dumbbell','Banco de ejercicios']];
  const selected=['agenda','bank','exercises'].includes(state.page)?state.page:state.page==='editor'&&state.templateId?'bank':'students';
  $('#navigation').innerHTML=items.map(([key,i,label])=>`<a class="nav-item ${selected===key?'active':''}" href="#${key}" ${selected===key?'aria-current="page"':''}>${icon(i)}${label}</a>`).join('');
  $('#breadcrumb').textContent=state.page==='editor'?`${state.templateId?'Banco':person().name} / ${routineStatus()}`:state.page==='metrics'?`${person().name} / Progreso`:state.page==='history'?`${person().name} / Historial`:state.page==='profile'?person().name:items.find(i=>i[0]===state.page)?.[2]||'Documento';
  $('.app-footer span:last-child').textContent=storageAvailable?'Guardado local en este navegador · PDF de muestra':'No se pudo guardar en el navegador · Cambios solo en esta pestaña';
}
function profileTabs(active){const historical=active==='editor'&&(state.archiveId||state.draftMode);return `<nav class="tabs student-tabs" aria-label="Secciones del alumno">${[['profile','Información y rutinas'],['editor','Rutina actual'],['metrics','Progreso'],['history','Historial']].map(([key,label])=>`<a class="tab ${active===key&&!historical?'active':''}" href="#${key}" data-live="true">${label}</a>`).join('')}${historical?`<span class="tab active context-tab">${routineStatus()}</span>`:''}</nav>`}
function draftCard(){const d=person().draft;return d?`<section class="draft-card"><div><span class="status-badge draft">BORRADOR · TODAVÍA NO ACTIVO</span><h2>${escapeHTML(d.name)}</h2><p>Base: ${escapeHTML(d.sourceName||'Rutina actual')} · ${d.weeks[0].length} días</p><p>${draftHasChanges(person())?'Cambios sin guardar. Abrí el borrador y pulsá Guardar borrador.':'Borrador guardado. La rutina actual sigue en uso.'}</p></div><div class="actions">${btn('Continuar borrador','open-draft','primary','edit')}${btn('Descartar','discard-draft','text')}</div></section>`:''}
function profileScreen(){let html=profile();html=html.replace('</aside><section>',`</aside><section>${draftCard()}`);html=html.replace('RUTINA ACTUAL</span>','RUTINA ACTUAL · EN USO</span>').replaceAll('>Usar de base<','>Copiar a borrador<').replaceAll('>Ver</button>','>Ver anterior</button>').replace('>Nueva rutina<','>Nuevo borrador<');return html}
function editorScreen(){
  const r=activeRoutine();if(!r)return `${studentHeader()}<div class="empty-state"><h1>Creá su primera rutina.</h1><p>Primero se prepara un borrador. Después elegís cuándo activarlo.</p>${btn('Crear borrador','create-routine','primary spaced','plus')}</div>`;
  state.day=Math.min(state.day,r.weeks[state.week-1].length-1);const d=currentDay(),status=routineStatus();
  const mode=state.templateId?'template':state.archiveId?'archive':state.draftMode?'draft':'current';
  const message={template:'Estás editando una base reutilizable. Las copias ya asignadas a alumnos no cambian.',archive:'Solo lectura. Abrir esta rutina no cambia la actual. Podés copiarla a un nuevo borrador.',draft:'Guardá tus cambios con «Guardar borrador». La rutina actual sigue en uso hasta que actives el borrador.',current:'Esta es la rutina en uso. Prepará un borrador para editarla y revisar los cambios antes de activarlos.'}[mode];
  const buttons=mode==='draft'?`${btn('Activar rutina','activate-draft','primary','check')}${btn('Guardar borrador','save-draft','','check')}${btn('Descartar','discard-draft','text')}`:mode==='archive'?btn('Copiar a borrador',`copy-archive:${r.id}`,'primary','copy'):mode==='current'?btn(person().draft?'Continuar borrador':'Preparar cambios',person().draft?'open-draft':'edit-current','primary','edit'):`${btn('Renombrar','rename-template','','edit')}${link('Volver al banco','bank','','left')}`;
  return `${state.templateId?'<a class="back-link" href="#bank">← Banco de rutinas</a>':studentHeader()}<div class="page-head editor-head"><div><span class="status-badge ${mode}">${status.toUpperCase()}</span><h1 style="margin-top:12px">${escapeHTML(r.name)}</h1><p>${state.templateId?'Base reutilizable':escapeHTML(person().name)} · ${dateLabel(r.date)} · 4 semanas</p></div><div class="actions">${buttons}${!state.templateId&&!state.draftMode?btn('Ver documento','current-pdf','','file'):''}</div></div>${!state.templateId?profileTabs('editor'):''}<div class="routine-state-note ${mode}">${icon(mode==='archive'?'history':mode==='current'?'check':'info')}<span>${message}</span></div><div class="editor-topline spaced"><div class="segmented">${[1,2,3,4].map(w=>`<button class="segment ${w===state.week?'active':''}" data-week="${w}">Semana ${w}</button>`).join('')}</div><span class="save-state">${icon(mode==='draft'&&draftHasChanges(person())?'edit':'check')}${isRoutineReadOnly()?'Solo lectura':mode==='draft'?draftSaveErrors.has(person().id)?'No se pudo guardar · Reintentá':draftHasChanges(person())?'Cambios sin guardar':'Borrador guardado':storageAvailable?'Guardado en este navegador':'Guardado local no disponible'} · v${r.revision}</span></div><div class="editor-layout ${isRoutineReadOnly()?'read-only-editor':''}">${!isRoutineReadOnly()?`<aside class="library desktop-library">${library()}</aside>`:''}<section><div class="day-tabs">${r.weeks[state.week-1].map((day,i)=>`<button class="day-tab ${state.day===i?'active':''}" data-day="${i}"><strong>Día ${i+1}</strong><span>${escapeHTML(day.title)}</span></button>`).join('')}${!isRoutineReadOnly()&&r.weeks[0].length<5?`<button class="day-tab add" data-action="add-day" aria-label="Agregar día">${icon('plus')}</button>`:''}</div><div class="day-editor-title"><div><h2>${escapeHTML(d.title)}</h2><span class="muted">Día ${state.day+1} · ${d.weekday}</span></div>${!isRoutineReadOnly()?`<div class="actions">${btn('Editar día','edit-day','text compact','edit')}<button class="btn mobile-library" data-action="library">${icon('plus')}Ejercicios</button></div>`:''}</div><div class="section-label">ENTRADA EN CALOR</div>${zoneView('mobility',d.mobility)}${zoneView('approximation',d.approximation)}<div class="section-label">ENTRENAMIENTO</div>${zoneView('main',d.main)}${!isRoutineReadOnly()?`<div class="help-line">${icon('info')}Los cambios en ejercicios se aplican desde la semana ${state.week} en adelante. ${state.draftMode?'La rutina activa no se modifica.':'Las rutinas de alumnos no se modifican.'}</div>`:''}</section></div>`;
}
function showPendingDraft(){modal('Ya hay un borrador pendiente',escapeHTML(person().draft.name),`<p class="modal-example">Podés continuar editándolo o descartarlo antes de crear otro. La rutina actual sigue activa.</p><div class="actions">${btn('Continuar borrador','open-draft','primary')}${btn('Descartar borrador','discard-draft')}</div>`)}
function lifecycleAction(command){const [kind,arg]=command.split(':');
  if(kind==='save-draft'){if(!person().draft)return true;const saved=saveDraft(person());closeModal();render();toast(saved?'Borrador guardado. La rutina actual sigue en uso.':'No se pudo guardar el borrador. Tus cambios siguen abiertos; reintentá.');return true}
  if(kind==='open-draft'){clearRoutineContext();state.draftMode=true;state.week=1;closeModal();go('editor');return true}
  if(kind==='edit-current'){if(person().draft){showPendingDraft();return true}assignRoutine(person().routine);persist();go('editor');return true}
  if(kind==='discard-draft'){modal('Descartar borrador',escapeHTML(person().draft?.name||''),'<p class="modal-example">La rutina actual y las anteriores se mantienen. Se elimina únicamente este borrador.</p>','Descartar borrador','confirm-discard');return true}
  if(kind==='confirm-discard'){if(!discardDraft(person())){error('No se pudo descartar el borrador. Reintentá.');return true}clearRoutineContext();closeModal();go('profile');return true}
  if(kind==='activate-draft'){
    const draft=person().draft;if(!draft)return true;
    if(draftHasChanges(person())){modal('Guardá el borrador primero','Tenés cambios pendientes.', '<p class="modal-example">Guardá el borrador antes de activar esta versión como rutina actual.</p>','Guardar borrador','save-draft');return true}
    const missing=draft.weeks.some(w=>w.some(d=>!d.main.length||['mobility','approximation','main'].some(zone=>d[zone].some(e=>!completeExercise(e)))));
    if(missing){modal('Completá el borrador','Hay días o ejercicios incompletos.','<p class="modal-example">Agregá al menos un ejercicio principal a cada día y completá peso, series y repeticiones de todos los ejercicios antes de activar.</p>');return true}
    modal('Activar esta rutina',escapeHTML(person().name),`<div class="activation-comparison"><div><span>ACTUAL</span><strong>${escapeHTML(person().routine?.name||'Sin rutina')}</strong><small>${person().routine?'Pasará a rutinas anteriores':'Primera rutina del alumno'}</small></div>${icon('arrow')}<div><span>NUEVA ACTUAL</span><strong>${escapeHTML(draft.name)}</strong><small>${draft.weeks[0].length} días · 4 semanas</small></div></div><p class="fineprint">Este es el único paso que reemplaza la rutina actual. Los resultados de entrenamientos anteriores se conservan.</p>`,'Activar como actual','confirm-activate');return true
  }
  if(kind==='confirm-activate'){
    const p=person();if(!p.draft||draftHasChanges(p))return true;
    const previous={routine:p.routine,archives:copy(p.archives),draft:p.draft,saved:savedDrafts.get(p.id),history:copy(p.history||[])};
    if(p.routine)p.archives.unshift(copy(p.routine));p.routine=copy(p.draft);p.routine.activatedAt=TODAY;recordHistory(p,'routine','Rutina activada',[p.routine.name,previous.routine?`Reemplaza a ${previous.routine.name}.`:'Primera rutina del alumno.',...routineChanges(previous.routine,p.routine)],{routineId:p.routine.id});delete p.draft;savedDrafts.delete(p.id);
    if(!persist()){p.routine=previous.routine;p.archives=previous.archives;p.draft=previous.draft;p.history=previous.history;if(previous.saved)savedDrafts.set(p.id,previous.saved);error('No se pudo activar la rutina. Reintentá.');return true}
    draftSaveErrors.delete(p.id);clearRoutineContext();closeModal();go('profile');toast('Nueva rutina activada. La anterior quedó en su historial.');return true
  }
  if(kind==='edit-template'){clearRoutineContext();state.templateId=DB.templates[Number(arg)].id;state.week=1;go('editor');return true}
  if(kind==='rename-template'){modal('Renombrar plantilla','Las rutinas de alumnos conservan sus nombres.',`<label class="field"><span>Nombre</span><input id="rename-template-input" maxlength="90" required value="${escapeHTML(activeRoutine().name)}"></label>`,'Guardar nombre','confirm-rename-template');return true}
  if(kind==='confirm-rename-template'){const name=$('#rename-template-input').value.trim();if(!name){error('Escribí un nombre.');return true}activeRoutine().name=name;closeModal();render();return true}
  return false;
}
function bankScreen(){return bank().replace(/data-action="preview-template:(\d+)"/g,'data-action="edit-template:$1"').replaceAll('>Ver rutina<','>Editar plantilla<')}

// Una configuración global alimenta todos los documentos y la vista previa del editor.
function brandStyle(config=DB.branding){return `--paper-accent:${config.accent};--paper-density:${config.density==='compact'?'6px':'10px'}`}
function logoURL(value){return /^(data:image\/(png|jpeg|webp);base64,|favicon\.svg$)/.test(value)?value:'favicon.svg'}
function paperHeader(config=DB.branding){return `<div class="paper-brand"><div class="paper-logo"><img src="${logoURL(config.logo)}" alt="Logo del entrenador">${escapeHTML(config.name)}</div><span class="eyebrow" style="font-size:8px">${escapeHTML(config.subtitle)}</span></div>`}
function paperFooter(page,total){return `<div class="paper-foot"><span>${escapeHTML(DB.branding.footer)}<br>${escapeHTML(person().name)} · ${dateLabel(TODAY)} · Datos de demostración</span><span>${page} / ${total}</span></div>`}
const documentBase=documents;
function documentsScreen(){return documentBase().replaceAll('<article class="paper">',`<article class="paper" style="${brandStyle()}">`).replace('Su rutina, en un documento.',`${routineStatus()}, en un documento.`)}

function groupMetrics(data){return [...new Set(data.map(m=>canonicalMuscleGroup(m.group)))].map(group=>{const rows=data.filter(m=>canonicalMuscleGroup(m.group)===group),comparable=rows.filter(m=>m.points.length>1&&m.percent!==null);return {group,load:[...rows].sort((a,b)=>b.best-a.best)[0],growth:[...comparable].sort((a,b)=>b.percent-a.percent)[0]||null}})}
function heatColor(item,all){if(!item)return '#dce4df';if(state.bodyMode==='load'){const ratio=item.load.best/Math.max(...all.map(g=>g.load.best),1);return ratio>.8?'#214f43':ratio>.5?'#538b66':ratio>.25?'#89b681':'#c1d9a6'}const n=item.growth?.percent;if(n===undefined)return '#dce4df';return n<0?'#d6aa82':n>=50?'#214f43':n>=25?'#538b66':n>0?'#9bbf87':'#d1ddc5'}
function bodyMap(data,interactive=true){
  const groups=groupMetrics(data),byGroup=Object.fromEntries(groups.map(g=>[g.group,g]));
  const region=(group,d)=>{const g=byGroup[group],value=state.bodyMode==='load'?(g?`${g.load.best} kg · ${g.load.name}`:'Sin registros'):(g?.growth?`${g.growth.percent>0?'+':''}${g.growth.percent}% · ${g.growth.name}`:'Sin evolución comparable');return d.split(/(?=M)/).filter(Boolean).map(part=>`<path class="muscle-region ${interactive&&state.group===group?'selected':''}" d="${part}" fill="${heatColor(g,groups)}" ${interactive?`data-body-group="${group}" role="button" tabindex="0" aria-label="${group}: ${escapeHTML(value)}" aria-pressed="${state.group===group}"`:''}><title>${group} · ${escapeHTML(value)}</title></path>`).join('')};
  const female=person().gender==='femenino',shadeId=interactive?'anatomy-shade':'anatomy-paper-shade';
  return `<svg class="body-map-svg" viewBox="0 0 440 550" role="group" aria-label="Mapa corporal ${female?'femenino':'masculino'} de ${state.bodyMode==='load'?'cargas registradas':'evolución de cargas'}"><defs><linearGradient id="${shadeId}" x1="0" x2="1"><stop stop-color="#173a2c" stop-opacity=".2"/><stop offset=".4" stop-color="#fff" stop-opacity=".2"/><stop offset="1" stop-color="#173a2c" stop-opacity=".15"/></linearGradient></defs><g transform="translate(10 0)">${anatomicalFigure({female,back:false,region,shadeId})}<text class="body-view-label" x="100" y="535">FRENTE</text></g><g transform="translate(230 0)">${anatomicalFigure({female,back:true,region,shadeId})}<text class="body-view-label" x="100" y="535">ESPALDA</text></g></svg>`;

}
function metricSelection(data){
  state.group=canonicalMuscleGroup(state.group);
  let group=data.filter(m=>canonicalMuscleGroup(m.group)===state.group);
  if(!group.length&&!MUSCLE_GROUPS.includes(state.group)&&data.length){state.group=canonicalMuscleGroup(data[0].group);group=data.filter(m=>canonicalMuscleGroup(m.group)===state.group)}
  const selected=group.find(m=>m.name===state.metricName)||group[0];
  state.metricName=selected?.name||'';
  return {group,selected};
}
function growthRows(data,interactive=true){const groups=groupMetrics(data).sort((a,b)=>(b.growth?.percent??-Infinity)-(a.growth?.percent??-Infinity));const max=Math.max(1,...groups.map(g=>Math.abs(g.growth?.percent||0)));return groups.map(g=>`<${interactive?'button':'div'} class="growth-row" ${interactive?`data-visual-group="${escapeHTML(g.group)}"`:''}><div><strong>${escapeHTML(g.group)}</strong><small>${escapeHTML(g.growth?.name||g.load.name)}</small></div><div class="growth-track"><span style="width:${Math.abs(g.growth?.percent||0)/max*100}%;background:${g.growth?.percent<0?'#d6aa82':'#8cb371'}"></span></div><strong class="growth-value">${g.growth?`${g.growth.percent>0?'+':''}${g.growth.percent}%`:'—'}</strong></${interactive?'button':'div'}>`).join('')}
function progressFocus(group,selected){
  if(!selected)return `<section class="card focus-card"><div class="card-head"><div><span class="eyebrow">${escapeHTML(state.group)}</span><h2>Sin datos en este período</h2></div></div><p>Cuando registres ejercicios de este grupo muscular, vas a poder consultar su evolución acá.</p></section>`;
  return `<section class="card focus-card"><div class="card-head"><div><span class="eyebrow">${escapeHTML(state.group)}</span><h2>Así fuiste avanzando</h2></div></div><label class="field"><span>Ejercicio</span><select id="metric-exercise">${group.map(m=>`<option ${m.name===selected.name?'selected':''}>${escapeHTML(m.name)}</option>`).join('')}</select></label><div class="progress-comparison"><div><span>Antes</span><strong>${selected.first}<small> kg</small></strong></div>${icon('arrow')}<div><span>Ahora</span><strong>${selected.last}<small> kg</small></strong></div><span class="progress-gain">${deltaLabel(selected)}</span></div><div class="chart-area">${chart(selected)}</div><p class="chart-context">${selected.points.length} registros · ${selected.points.every(p=>p.reps===selected.points[0].reps)?selected.points[0].reps+' repeticiones por registro':'Repeticiones variables'} · ${selected.name.includes('mancuerna')?'Peso por mancuerna':'Carga externa'}</p></section>`;
}
function progressScreen(){
  const data=progressData(),{group,selected}=metricSelection(data),leaders=groupMetrics(data).filter(g=>g.growth).sort((a,b)=>b.growth.percent-a.growth.percent),lead=leaders[0]?.growth;
  return `${studentHeader()}<div class="page-head"><div><span class="eyebrow">TU EVOLUCIÓN, A LA VISTA</span><h1 style="margin-top:10px">Cada vez más lejos.</h1><p>${escapeHTML(person().name)} · Tu recorrido de entrenamiento</p></div>${btn('Ver PDF','progress-pdf','primary','file')}</div>${profileTabs('metrics')}<div class="progress-top"><div>${periodControls()}<p class="period-label">${rangeLabel()}</p></div>${state.period==='custom'?'':`<span class="tag">${data.length} ejercicios con registros</span>`}</div>${state.period==='custom'?`<div class="date-range"><label class="field"><span>Desde</span><input id="date-start" type="date" value="${state.customStart}"></label><label class="field"><span>Hasta</span><input id="date-end" type="date" value="${state.customEnd}"></label>${btn('Ver período','custom-dates')}</div>`:''}${data.length?`<div class="visual-progress-layout"><section class="card body-card"><div class="card-head"><div><h2>Tu mapa de progreso</h2><p>Tocá un músculo para explorar su evolución.</p></div><div class="body-mode"><button data-body-mode="progress" class="${state.bodyMode==='progress'?'active':''}">Evolución</button><button data-body-mode="load" class="${state.bodyMode==='load'?'active':''}">Cargas</button></div></div><div class="body-canvas">${bodyMap(data)}</div><div class="body-legend"><span>${state.bodyMode==='progress'?'Menor avance':'Menor carga'}</span><i></i><span>${state.bodyMode==='progress'?'Mayor avance':'Mayor carga'}</span><small>Gris: sin datos comparables</small></div><p class="map-definition">${state.bodyMode==='progress'?'Color: mejor cambio porcentual de un ejercicio de cada grupo.':'Color: mayor carga externa registrada en un ejercicio de cada grupo. Kilos de ejercicios distintos no equivalen a fuerza muscular.'}</p></section><aside class="progress-story"><section class="progress-highlight"><div class="eyebrow">${lead&&lead.percent>0?'TU MAYOR AVANCE':'TU RECORRIDO'}</div><strong>${lead&&lead.percent>0?'+'+lead.percent+'%':'Cada paso cuenta'}</strong><h3>${escapeHTML(lead?.name||selected?.name||'Tus entrenamientos')}</h3><p>${lead?`${lead.first} → ${lead.last} kg durante este período.`:'Los próximos registros mostrarán cómo evolucionás.'}</p><span>Cambio de carga en el mismo ejercicio</span></section>${progressFocus(group,selected)}</aside></div><section class="card progress-ranking"><div class="card-head"><div><h2>Tus avances, grupo por grupo</h2><p>Mejor cambio de carga de un ejercicio por grupo, dentro del período.</p></div><span class="tag">Cambio porcentual</span></div><div class="growth-list">${growthRows(data)}</div></section><p class="fineprint">Mapa ilustrativo con datos de demostración. Compara el recorrido de cada ejercicio; no es un diagnóstico ni una medición de fuerza absoluta del músculo.</p>`:`<section class="card">${emptyState()}</section>`}`;
}
function progressPaper(){const data=progressData(),groups=groupMetrics(data).map(g=>g.group);return `<article class="paper">${paperHeader()}<h2>TU PROGRESO</h2><p class="paper-person">${escapeHTML(person().name)}</p><p class="paper-sub">${rangeLabel()} · Generado el 23/09/2026</p>${data.length?`<h3>Tu mapa de ${state.bodyMode==='load'?'cargas':'evolución'}</h3><div class="paper-body-map">${bodyMap(data,false)}</div><p class="fineprint">${state.bodyMode==='load'?'Color: mayor carga de un ejercicio por grupo.':'Color: mejor cambio porcentual de un ejercicio por grupo.'} Gris: sin datos comparables. No representa fuerza absoluta entre músculos.</p><div class="growth-list">${growthRows(data,false)}</div>`:emptyState()}${paperFooter(1,groups.length+1)}</article>${groups.map((g,i)=>`<article class="paper">${paperHeader()}<h2>${escapeHTML(g)}</h2><p class="paper-sub">${escapeHTML(person().name)} · ${rangeLabel()}</p>${data.filter(m=>canonicalMuscleGroup(m.group)===g).map(m=>`<section class="paper-exercise"><h3>${escapeHTML(m.name)}</h3><div class="paper-meta"><span>${m.first} kg → <strong>${m.last} kg</strong></span><strong>${deltaLabel(m)}</strong></div>${chart(m)}<p class="paper-sub">${m.points.length} registros · Carga externa en el mismo ejercicio</p></section>`).join('')}${paperFooter(i+2,groups.length+1)}</article>`).join('')}`}

views.profile=profileScreen;views.editor=editorScreen;views.bank=bankScreen;views.metrics=progressScreen;views.documents=documentsScreen;
function selectBodyGroup(group){state.group=group;state.metricName='';render()}
document.addEventListener('click',event=>{const region=event.target.closest('[data-body-group],[data-visual-group],[data-body-mode]');if(!region)return;if(region.dataset.bodyMode){state.bodyMode=region.dataset.bodyMode;render()}else selectBodyGroup(region.dataset.bodyGroup||region.dataset.visualGroup)});
document.addEventListener('keydown',event=>{if(event.target.matches('[data-body-group]')&&['Enter',' '].includes(event.key)){event.preventDefault();selectBodyGroup(event.target.dataset.bodyGroup)}});
