/* Training is a working surface: inputs stay mounted while autosave runs. */
const trainingFieldLabels={weight:'Peso (kg)',sets:'Series',reps:'Repeticiones',microRest:'Micro (s)',macroRest:'Macro (s)',macroTarget:'Descanso macro'};
const trainingBlockState=new Map();
function rememberTrainingLayout(){
  document.querySelectorAll('[data-session-block]').forEach(el=>trainingBlockState.set(el.dataset.sessionBlock,el.open));
  try{sessionStorage.setItem('pulso-training-blocks',JSON.stringify([...trainingBlockState]))}catch{}
}
try{for(const [key,value] of JSON.parse(sessionStorage.getItem('pulso-training-blocks')||'[]'))trainingBlockState.set(key,Boolean(value))}catch{}
function trainingInput(target,field,attrs='',readonly=false){
  const label=trainingFieldLabels[field],value=target[field]??'',max=field==='weight'?150:field==='sets'?4:field==='reps'?15:3600,min=['sets','reps'].includes(field)?1:0;
  return `<label class="training-field"><span>${label}</span><input type="number" inputmode="numeric" min="${min}" max="${max}" step="1" value="${escapeHTML(value)}" aria-label="${escapeHTML(label+' · '+(target.name||'Bloque'))}" ${attrs} data-field="${field}" ${readonly?'disabled':''} placeholder="—"><small class="field-error" aria-live="polite"></small></label>`;
}
function activeSessionSelector(){
  const sessions=(DB.sessions||[]).filter(s=>s.status==='open');
  return `<section class="active-training" aria-label="Entrenando ahora"><div class="active-heading"><span class="eyebrow">ENTRENANDO AHORA</span><span class="tag green">${sessions.length} activos</span></div>${sessions.length?`<div class="active-students">${sessions.map(s=>{const p=DB.people.find(p=>p.id===s.personId);return `<button class="active-student ${state.sessionId===s.id&&state.page==='training'?'selected':''}" data-action="train-open:${s.id}" aria-pressed="${state.sessionId===s.id&&state.page==='training'}">${avatar(p)}<span><strong>${escapeHTML(p.name)}</strong><small>${escapeHTML(s.dayTitle)} · <span data-pending-session="${s.id}">En curso</span></small></span></button>`}).join('')}</div>`:'<p class="muted">Iniciá un entrenamiento desde la agenda o agregá a quien acaba de llegar.</p>'}</section>`;
}
function trainingAgenda(){
  const visits=calendarVisits(TODAY),closed=visits.filter(x=>x.visit.status==='closed').length,pending=visits.filter(x=>x.visit.status==='pending').length;
  const labels={pending:'Pendiente',open:'En curso',closed:'Finalizado',absent:'No asistió',rescheduled:'Reprogramado'};
  return `<div class="page-head"><div><div class="eyebrow">${new Date(TODAY+'T12:00:00').toLocaleDateString('es-AR',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}</div><h1>Tu día, en movimiento.</h1><p>Registrá cada ajuste mientras entrenan.</p></div><div class="actions">${btn('Agregar entrenamiento ahora','train-quick','primary','plus')}${btn('Copias de respaldo','backup-open','','download')}</div></div>${activeSessionSelector()}<div class="training-stats"><span><strong>${pending}</strong> pendientes</span><span><strong>${closed}</strong> finalizados</span><span><strong>${visits.filter(x=>x.visit.status==='absent').length}</strong> faltas</span></div><section class="card agenda-full"><div class="card-head"><div><h2>Agenda de hoy</h2><p>Iniciá, reprogramá o registrá una falta.</p></div>${btn('Ver calendario','calendar','','calendar')}</div>${visits.map(({person:p,visit:v,time})=>{const session=(DB.sessions||[]).find(s=>s.visitId===v.id);return `<div class="person-row agenda-visit"><div class="agenda-visit-time">${escapeHTML(time||'Sin hora')}</div>${avatar(p)}<a class="person-details" href="#profile" data-person="${DB.people.indexOf(p)}"><strong>${escapeHTML(p.name)}</strong><p>${escapeHTML(p.routine?.name||'Rutina por crear')}</p></a><div class="row-actions">${tag(labels[v.status],v.status==='open'||v.status==='closed'?'green':v.status==='absent'?'amber':'')}${v.status==='pending'?`${btn('Iniciar',`train-visit:${v.id}`,'','dumbbell')}${btn('No asistió',`train-absent:${v.id}`,'text compact')}${btn('Reprogramar',`train-reschedule:${v.id}`,'text compact','calendar')}`:session?btn(v.status==='open'?'Continuar':'Ver registro',`train-open:${session.id}`,'compact'):''}</div></div>`}).join('')||'<p class="card-pad muted">No hay visitas previstas. Podés agregar un entrenamiento ahora.</p>'}</section>`;
}
function trainingScreen(){
  const s=DB.sessions?.find(x=>x.id===state.sessionId);if(!s)return `${activeSessionSelector()}<div class="card card-pad"><h1>Elegí un entrenamiento</h1><p>Los entrenamientos abiertos están arriba.</p>${link('Volver a la agenda','agenda')}</div>`;
  const p=DB.people.find(x=>x.id===s.personId),closed=s.status==='closed';
  return `${activeSessionSelector()}<div class="page-head training-title"><div><a class="back-link" href="#agenda">← Agenda</a><h1>${escapeHTML(p.name)}</h1><p>${escapeHTML(s.dayTitle)} · Semana ${s.week} · ${s.period} · ${closed?'Finalizado':'En curso'}</p></div>${closed?tag('Entrenamiento finalizado','green'):btn('Finalizar entrenamiento',`train-finish:${s.id}`,'primary','check')}</div><div class="training-savebar" role="status"><span data-training-status>Guardado en este dispositivo</span><div class="actions"><button class="btn compact" data-action="train-retry" data-save-retry hidden>Reintentar</button><button class="btn compact" data-action="train-conflict" data-save-conflict hidden>Revisar otra versión</button></div></div><p class="fineprint">${closed?'Este registro conserva lo realizado. Las correcciones quedan en el historial.':'Los cambios se guardan solos y actualizan la rutina desde esta semana. Micro: entre ejercicios. Macro: entre series o bloques.'}</p><div class="session-blocks">${s.blocks.map((b,bi)=>{
    const attrs=`data-live-session="${s.id}" data-block-id="${b.id}"`;
    return `<details class="card session-block" data-session-block="${s.id}:${b.id}" ${(trainingBlockState.get(`${s.id}:${b.id}`)??b.type==='main')?'open':''}><summary><span class="block-number">${String(bi+1).padStart(2,'0')}</span><span><strong>${escapeHTML(b.name)}</strong><small>${b.exercises.length} ejercicios</small></span>${icon('down')}</summary><div class="block-rest">${trainingInput(b,'macroRest',attrs,closed)}<label class="training-field"><span>Aplicar macro</span><select ${attrs} data-field="macroTarget" aria-label="Aplicar macro · ${escapeHTML(b.name)}" ${closed?'disabled':''}><option value="series" ${b.macroTarget==='series'?'selected':''}>Entre series</option><option value="blocks" ${b.macroTarget==='blocks'?'selected':''}>Entre bloques</option></select></label></div><div class="session-exercises">${b.exercises.map(e=>`<article class="session-exercise ${e.skipped?'skipped':''}"><div class="session-exercise-name"><strong>${escapeHTML(e.name)}</strong><small>${escapeHTML(e.group)}</small>${closed?'':`<label class="skip-field"><input type="checkbox" data-skip-session="${s.id}" data-block-id="${b.id}" data-exercise-id="${e.id}" ${e.skipped?'checked':''}>No se realizó</label>`}</div><div class="session-values">${['weight','sets','reps','microRest'].map(field=>trainingInput(e,field,`${attrs} data-exercise-id="${e.id}"`,closed||e.skipped)).join('')}</div>${closed&&!e.skipped?btn('Corregir',`train-correct:${s.id}:${b.id}:${e.id}`,'text compact'):''}</article>`).join('')||'<p class="card-pad muted">Bloque sin ejercicios.</p>'}</div></details>`;
  }).join('')}</div>`;
}
function routineBlockView(b){
  const readonly=isRoutineReadOnly(),attrs=`data-routine-block="${b.id}"`;
  return `<section class="block exercise-zone" data-zone="${b.id}"><div class="block-title"><h3>${icon(b.type==='main'?'dumbbell':'fire')}${escapeHTML(b.name)}</h3>${!readonly?`<div class="actions">${btn('Editar',`block-rename:${b.id}`,'text compact')}${btn('↑',`block-up:${b.id}`,'compact')}${btn('↓',`block-down:${b.id}`,'compact')}${btn('Quitar',`block-remove:${b.id}`,'text compact')}</div>`:tag(zoneLabel[b.type])}</div><div class="block-rest">${trainingInput(b,'macroRest',attrs,readonly)}<label class="training-field"><span>Aplicar macro</span><select ${attrs} data-field="macroTarget" aria-label="Aplicar macro · ${escapeHTML(b.name)}" ${readonly?'disabled':''}><option value="series" ${b.macroTarget==='series'?'selected':''}>Entre series</option><option value="blocks" ${b.macroTarget==='blocks'?'selected':''}>Entre bloques</option></select></label></div>${b.exercises.map(e=>`<div class="session-exercise"><div class="session-exercise-name"><strong>${escapeHTML(e.name)}</strong><small>${escapeHTML(e.group)}</small>${!readonly?`<div class="actions">${btn('↑',`block-ex-up:${b.id}:${e.id}`,'compact')}${btn('↓',`block-ex-down:${b.id}:${e.id}`,'compact')}${btn('Quitar',`block-ex-remove:${b.id}:${e.id}`,'text compact')}</div>`:''}</div><div class="session-values">${['weight','sets','reps','microRest'].map(field=>trainingInput(e,field,`${attrs} data-exercise-id="${e.id}"`,readonly)).join('')}</div></div>`).join('')||'<p class="zone-empty">Todavía no agregaste ejercicios.</p>'}${!readonly?`<button class="drop-zone" data-action="block-ex-add:${b.id}">${icon('plus')}Arrastrá acá o agregá un ejercicio</button>`:''}</section>`;
}
views.agenda=trainingAgenda;views.training=trainingScreen;
