const search = (id, placeholder) => `<label class="search">${icon('search')}<input id="${id}" type="search" aria-label="${placeholder}" placeholder="${placeholder}"></label>`;
const studentHeader=()=>`<a class="back-link" href="#profile">${icon('left')}${escapeHTML(person().name)}</a>`;
const stat=(label,value,note,glyph='chart',dark=false)=>`<div class="stat ${dark?'dark':''}"><div class="stat-label">${label}</div><div class="stat-icon">${icon(glyph)}</div><div class="stat-value">${value}</div><div class="stat-note">${note}</div></div>`;
const groupNames=()=>[...new Set(DB.library.map(e=>e.group))];
const zoneLabel={mobility:'Movilidad',approximation:'Aproximaciones',main:'Parte principal'};
const emptyState=()=>`<div class="empty-state">${icon('chart')}<h2>Todavía no hay registros</h2><p>Probá otro período para ver la evolución.<br>Sin registros no significa que no haya progreso.</p></div>`;
function selectRange(name,min,max,value,suffix='',required=false){const empty=value===null||value===undefined||value==='';return `<select name="${name}" ${required?'required':''} aria-label="${name==='weight'?'Peso en kg':name==='sets'?'Series':'Repeticiones'}"><option value="" ${empty?'selected':''}>Sin definir</option>${Array.from({length:max-min+1},(_,i)=>min+i).map(n=>`<option value="${n}" ${!empty&&n===Number(value)?'selected':''}>${n}${suffix}</option>`).join('')}</select>`}
function valueControls(e,required=false){return `<div class="value-controls"><label><span>Peso</span>${selectRange('weight',0,150,e.weight,' kg',required)}</label><label><span>Series</span>${selectRange('sets',1,4,e.sets,'',required)}</label><label><span>Reps</span>${selectRange('reps',1,15,e.reps,'',required)}</label></div>`}

function navigation(){
  const items=[['agenda','calendar','Agenda'],['students','users','Alumnos'],['bank','routine','Banco de rutinas']];
  const active=state.page==='agenda'?'agenda':state.page==='bank'?'bank':'students';
  $('#navigation').innerHTML=items.map(([page,i,label])=>`<a class="nav-item ${active===page?'active':''}" href="#${page}" ${active===page?'aria-current="page"':''}>${icon(i)}${label}</a>`).join('');
  $('#breadcrumb').textContent={agenda:'Agenda',students:'Alumnos',profile:person().name,editor:`${person().name} / Rutina`,metrics:`${person().name} / Progreso`,documents:`${person().name} / Documento`,bank:'Banco de rutinas'}[state.page];
}
function profileTabs(active){return `<nav class="tabs student-tabs" aria-label="Secciones del alumno">${[['profile','Información y rutinas'],['editor','Rutina actual'],['metrics','Progreso'],['history','Historial']].map(([key,label])=>`<a class="tab ${active===key?'active':''}" href="#${key}" data-live="true">${label}</a>`).join('')}</nav>`}
function agenda(){
  const visitors=calendarVisits(TODAY).map(({person:p,time})=>({p,time,i:DB.people.indexOf(p)}));
  const done=visitors.filter(({p})=>p.attendance==='Confirmado').length;
  return `<div class="page-head"><div><div class="eyebrow" style="margin-bottom:10px">MIÉRCOLES, 23 DE SEPTIEMBRE DE 2026</div><h1>Tu agenda de hoy.</h1><p>Confirmá cada entrenamiento y ajustá solo lo que cambió.</p></div>${btn('Ver calendario','calendar','','calendar')}</div><div class="stats">${stat('Alumnos para hoy',visitors.length,'Asistencias previstas','users')}${stat('Entrenamientos confirmados',`${done} <small>/ ${visitors.length}</small>`,'Resultados del día','check',true)}${stat('Por confirmar',visitors.length-done,'Entrenamientos pendientes','clock')}</div><section class="card agenda-full"><div class="card-head"><div><h2>Esta semana</h2><p>21 – 27 de septiembre</p></div><span class="tag">Miércoles 23</span></div><div class="week-strip">${WEEKDAYS.map((d,i)=>`<button class="calendar-day ${i===2?'selected':''}" data-action="calendar:${calendarWeekDates()[i]}"><span>${d}</span><strong>${21+i}</strong><span class="day-dot"></span></button>`).join('')}</div><div class="list-toolbar"><span class="eyebrow">ENTRENAMIENTOS DEL DÍA</span><span class="muted">${visitors.length} alumnos</span></div>${visitors.map(({p,i,time})=>{const d=p.routine?.weeks[1][p.sessionIndex]||p.routine?.weeks[0][0];return `<div class="person-row agenda-visit"><div class="agenda-visit-time">${time?`<time datetime="${TODAY}T${escapeHTML(time)}">${escapeHTML(time)}</time>`:'<span>Sin horario</span>'}</div>${avatar(p)}<a class="person-details" href="#profile" data-person="${i}"><div class="person-name">${escapeHTML(p.name)}</div><p>${d?`Día ${Math.min(p.sessionIndex+1,p.routine.weeks[1].length)} · ${escapeHTML(d.title)}`:'Rutina por crear'}</p></a><div class="row-actions">${tag(p.attendance,p.attendance==='Confirmado'?'green':p.attendance==='Reprogramado'?'blue':'')}${btn(p.attendance==='Confirmado'?'Ver registro':'Confirmar',`confirm:${i}`,p.attendance==='Confirmado'?'text':'','check')}<button class="icon-btn" data-action="reschedule:${i}" aria-label="Reprogramar a ${escapeHTML(p.name)}">${icon('calendar')}</button></div></div>`}).join('')||'<p class="card-pad muted">No hay visitas previstas para hoy.</p>'}</section>`;
}
function studentRows(query=''){return DB.people.map((p,i)=>({p,i})).filter(({p})=>normalize(p.name).includes(normalize(query))).map(({p,i})=>`<tr><td><a class="table-person" href="#profile" data-person="${i}">${avatar(p)}<div class="person-name">${escapeHTML(p.name)}<small>${p.weekdays.length} días por semana</small></div></a></td><td class="days-col">${p.weekdays.join(' · ')}</td><td class="routine-col">${escapeHTML(p.routine?.name||'Por crear')}<br><span class="tag green" style="margin-top:6px">${p.routine?'Rutina personalizada':'Sin rutina'}</span></td><td><a class="icon-btn" href="#profile" data-person="${i}" aria-label="Ver a ${escapeHTML(p.name)}">${icon('chevron')}</a></td></tr>`).join('')||'<tr><td colspan="4">No hay alumnos que coincidan.</td></tr>'}
function students(){return `<div class="page-head"><div><h1>Tus alumnos</h1><p>Su información, sus rutinas y su progreso.</p></div>${btn('Nuevo alumno','new-student','primary','plus')}</div><section class="card"><div class="card-head">${search('student-search','Buscar por nombre o apellido')}<span class="tag green">${DB.people.length} alumnos de muestra</span></div><div class="table-wrap"><table class="data-table students-table"><thead><tr><th>ALUMNO</th><th class="days-col">DÍAS HABITUALES</th><th class="routine-col">RUTINA ACTUAL</th><th></th></tr></thead><tbody id="student-rows">${studentRows()}</tbody></table></div></section>`}
function profile(){const p=person(),r=p.routine;return `<div class="page-head"><div><a class="back-link" href="#students">${icon('left')}Todos los alumnos</a><h1>${escapeHTML(p.name)}</h1><p>${p.weekdays.length} días por semana · ${p.weekdays.join(' · ')}</p></div>${btn('Editar datos','edit-profile','','edit')}</div>${profileTabs('profile')}<div class="profile-layout"><aside class="card card-pad"><h3>Información del alumno</h3><div class="profile-info"><span>Nombre</span><strong>${escapeHTML(p.name.split(' ')[0])}</strong><span>Apellido</span><strong>${escapeHTML(p.name.split(' ').slice(1).join(' '))}</strong><span>Género</span><strong>${genderLabel(p)}</strong><span>Frecuencia</span><strong>${p.weekdays.length} días por semana</strong><span>Días y horarios</span><ul class="profile-schedule">${p.weekdays.map(day=>`<li><span>${weekdayName(day)}</span><strong>${escapeHTML(p.scheduleTimes?.[day]??p.scheduleTime??'')||'Sin horario'}</strong></li>`).join('')}</ul></div><p class="fineprint">Para una visita excepcional, cambiá la fecha desde la agenda.</p>${link('Ver su progreso','metrics','w-full spaced','chart')}</aside><section><div class="card"><div class="card-head"><div><span class="eyebrow">RUTINA ACTUAL</span><h2 style="margin-top:9px">${escapeHTML(r?.name||'Creá su primera rutina')}</h2><p>${r?`${dateLabel(r.date)} · 4 semanas · ${r.weeks[0].length} días`:'Empezá desde cero o usá una rutina como base.'}</p></div>${r?btn('Abrir rutina','open-current','primary','arrow'):btn('Crear rutina','create-routine','primary','plus')}</div>${r?`<div class="profile-days">${r.weeks[0].map((d,i)=>`<div class="summary-day"><div><span>DÍA ${i+1} · ${d.weekday}</span><strong>${escapeHTML(d.title)}</strong><p>${d.main.length} ejercicios + entrada en calor</p></div><button class="icon-btn" data-action="open-day:${i}" aria-label="Ver día ${i+1} de la rutina">${icon('chevron')}</button></div>`).join('')}</div><div class="routine-footer"><span>Una rutina · Todos los días en un mismo documento</span>${btn('Ver PDF','routine-pdf','','file')}</div>`:''}</div><section class="card spaced"><div class="card-head"><div><h2>Rutinas anteriores</h2><p>El recorrido de ${escapeHTML(p.name.split(' ')[0])}, mes a mes.</p></div>${r?btn('Nueva rutina','create-routine','compact','plus'):''}</div>${p.archives.map(r=>`<div class="archive-row"><div class="archive-icon">${icon('file')}</div><div><strong>${escapeHTML(r.name)}</strong><p>${dateLabel(r.date)} · 4 semanas · ${r.weeks[0].length} días</p></div><div class="actions">${btn('Ver',`archive:${r.id}`,'compact')}${btn('Usar de base',`copy-archive:${r.id}`,'text compact','copy')}</div></div>`).join('')||'<p class="card-pad muted">Las rutinas anteriores aparecerán acá al crear una nueva.</p>'}</section></section></div>`}
function library(){return `<h2>Ejercicios</h2><p class="library-intro">Arrastrá a cualquier zona de la rutina.</p>${search('exercise-search','Buscar ejercicio')}<div class="eyebrow">GRUPOS MUSCULARES</div>${groupNames().map((g,i)=>`<details ${i===0?'open':''}><summary>${escapeHTML(g)}<span>${DB.library.filter(e=>e.group===g).length}</span></summary>${DB.library.filter(e=>e.group===g).map(e=>`<div class="exercise-item" draggable="true" data-drag="${e.id}" data-exercise="${escapeHTML(normalize(e.name))}"><span class="grip">⠿</span><span>${escapeHTML(e.name)}</span><button data-action="add-exercise:${e.id}" aria-label="Agregar ${escapeHTML(e.name)}">+</button></div>`).join('')}</details>`).join('')}${btn('Crear ejercicio','new-exercise','','plus')}`}
function zoneView(zone,rows){return `<section class="block exercise-zone" data-zone="${zone}"><div class="block-title"><h3>${icon(zone==='main'?'dumbbell':'fire')}${zoneLabel[zone]}</h3><span class="tag">${rows.length} ejercicios</span></div>${rows.length?`<table class="exercise-table"><thead><tr><th>EJERCICIO</th><th>SERIES</th><th>REPS</th><th>KG</th><th></th></tr></thead><tbody>${rows.map((e,i)=>`<tr><td class="name"><strong>${escapeHTML(e.name)}</strong><small>${escapeHTML(e.group)}</small></td><td data-label="Series"><span class="cell">${e.sets??'—'}</span></td><td data-label="Reps"><span class="cell">${e.reps??'—'}</span></td><td data-label="Kg"><span class="cell">${e.weight??'—'}</span></td><td>${!isRoutineReadOnly()?`<div class="exercise-row-actions"><button class="icon-btn" data-action="edit-exercise:${zone}:${e.id}" aria-label="Editar ${escapeHTML(e.name)}" title="Editar ejercicio">${icon('edit')}</button><button class="remove-exercise-btn" data-action="remove-exercise:${zone}:${e.id}" aria-label="Quitar ${escapeHTML(e.name)}" title="Quitar desde esta semana">${icon('trash')}<span>Quitar</span></button></div>`:''}</td></tr>`).join('')}</tbody></table>`:'<p class="zone-empty">Todavía no agregaste ejercicios.</p>'}${!isRoutineReadOnly()?`<button class="drop-zone" data-action="choose-zone:${zone}">${icon('plus')}Arrastrá acá o elegí un ejercicio</button>`:''}</section>`}
function editor(){const r=activeRoutine();if(!r)return `${studentHeader()}<div class="empty-state"><h1>Su primera rutina empieza acá.</h1><p>Podés crearla desde cero o copiar una base.</p>${btn('Crear rutina','create-routine','primary spaced','plus')}</div>`;state.day=Math.min(state.day,r.weeks[state.week-1].length-1);const d=currentDay();return `${studentHeader()}<div class="page-head editor-head"><div><h1>${escapeHTML(r.name)}</h1><p>${escapeHTML(person().name)} · ${dateLabel(r.date)} · Una rutina de 4 semanas</p></div><div class="actions">${!isRoutineReadOnly()?btn('Guardar en banco','save-template','','copy'):tag('Rutina anterior · Solo lectura')}${btn('Vista previa PDF','current-pdf','primary','file')}</div></div>${profileTabs('editor')}${state.archiveId?`<div class="preview-state spaced">Estás viendo una rutina anterior. ${btn('Usar como base',`copy-archive:${r.id}`,'compact','copy')}</div>`:''}<div class="editor-topline spaced"><div class="segmented">${[1,2,3,4].map(w=>`<button class="segment ${w===state.week?'active':''}" data-week="${w}">Semana ${w}</button>`).join('')}</div><span class="save-state">${icon('check')}${state.archiveId?'Versión conservada':'Cambios temporales · Versión '+r.revision}</span></div><div class="editor-layout ${state.archiveId?'read-only-editor':''}">${!isRoutineReadOnly()?`<aside class="library desktop-library">${library()}</aside>`:''}<section><div class="day-tabs">${r.weeks[state.week-1].map((d,i)=>`<button class="day-tab ${i===state.day?'active':''}" data-day="${i}"><strong>Día ${i+1}</strong><span>${escapeHTML(d.title)}</span></button>`).join('')}${!state.archiveId&&r.weeks[0].length<5?`<button class="day-tab add" data-action="add-day" aria-label="Agregar día">${icon('plus')}</button>`:''}</div><div class="day-editor-title"><div><h2>${escapeHTML(d.title)}</h2><span class="muted">Día ${state.day+1} · ${d.weekday}</span></div><div class="actions">${!isRoutineReadOnly()?`${btn('Editar día','edit-day','text compact','edit')}<button class="btn mobile-library compact" data-action="library">${icon('plus')}Ejercicios</button>`:''}</div></div><div class="section-label">ENTRADA EN CALOR</div>${zoneView('mobility',d.mobility)}${zoneView('approximation',d.approximation)}<div class="section-label">ENTRENAMIENTO</div>${zoneView('main',d.main)}<p class="help-line">${icon('info')}Editás este día dentro de una única rutina. Los cambios aplican desde la semana ${state.week} en adelante.</p></section></div>`}
function bank(){return `<div class="page-head"><div><h1>Banco de rutinas</h1><p>Plantillas creadas desde cero para organizar tus rutinas.</p></div>${btn('Nueva plantilla','new-template','primary','plus')}</div><div class="bank-grid">${DB.templates.map((r,i)=>`<article class="card template-card"><div class="template-top"><span class="template-symbol">${icon('routine')}</span><span class="tag">${r.weeks[0].length} días · 4 semanas</span></div><h2>${escapeHTML(r.name)}</h2><div class="template-days">${r.weeks[0].map((d,i)=>`<p><span>0${i+1}</span>${escapeHTML(d.title)}</p>`).join('')}</div><div class="actions">${btn('Ver rutina',`preview-template:${i}`,'')}</div></article>`).join('')}</div><div class="aside-note bank-note"><h3>Una base compartida. Un plan personal.</h3><p>Creá cada plantilla desde cero. Podés elegir una plantilla al preparar la rutina desde el perfil de un alumno.</p></div>`}
function periodControls(){return `<div class="segmented">${[['month','Último mes'],['six','Últimos 6 meses'],['year','Último año'],['custom','Personalizado']].map(([key,label])=>`<button class="segment ${state.period===key?'active':''}" data-period="${key}">${label}</button>`).join('')}</div>`}
function chart(metric){
  if(!metric?.points.length)return '';
  const points=metric.points,first=Date.parse(points[0].date),last=Date.parse(points.at(-1).date);
  const max=Math.max(5,Math.ceil(Math.max(...points.map(p=>p.weight))*1.15/5)*5);
  const coords=points.map(p=>[first===last?310:50+(Date.parse(p.date)-first)/(last-first)*510,190-p.weight/max*160]);
  const line=coords.map(p=>p.join(',')).join(' ');
  const dates=first===last?[first]:Array.from({length:4},(_,i)=>first+(last-first)*i/3);
  return `<svg class="chart" viewBox="0 0 610 230" role="img" aria-label="${escapeHTML(metric.name)}: ${metric.first} a ${metric.last} kg"><path d="M${coords[0][0]} 195 L${line.replaceAll(' ',' L')} L${coords.at(-1)[0]} 195Z" fill="#eaf2e0"/>${[0,.5,1].map(v=>`<line class="chart-grid" x1="45" x2="575" y1="${190-v*160}" y2="${190-v*160}"/><text class="chart-label" x="8" y="${194-v*160}">${Math.round(max*v)}</text>`).join('')}<polyline class="chart-line" points="${line}"/>${coords.map(p=>`<circle class="chart-dot" cx="${p[0]}" cy="${p[1]}" r="3.5"/>`).join('')}${dates.map((d,i)=>`<text class="chart-label" text-anchor="middle" x="${dates.length===1?310:50+i*510/3}" y="220">${new Date(d).toLocaleDateString('es-AR',{day:'numeric',month:'short',timeZone:'UTC'})}</text>`).join('')}<text class="chart-label" x="8" y="14">kg</text></svg>`;
}

function deltaLabel(m){return m.points.length<2?'Primer registro':m.delta===0?'Carga sostenida':`${m.delta>0?'+':''}${m.delta} kg${m.percent!==null?' · '+(m.percent>0?'+':'')+m.percent+'%':''}`}
function muscleCards(data,interactive=true){return [...new Set(data.map(d=>d.group))].map(group=>{const exercises=data.filter(m=>m.group===group);const strongest=[...exercises].sort((a,b)=>b.best-a.best)[0];const gain=[...exercises].sort((a,b)=>b.delta-a.delta)[0];return `<${interactive?'button':'article'} class="muscle-progress-card ${state.group===group?'selected':''}" ${interactive?`data-group="${group}"`:''}><div class="muscle-card-head"><h3>${group}</h3>${icon('chart')}</div><div class="muscle-big">${strongest.best}<small> kg</small></div><p class="muscle-description">Mayor carga registrada<br><strong>${escapeHTML(strongest.name)}</strong></p><div class="gain-line">${icon('arrow')} ${deltaLabel(gain)}</div><p class="gain-context">${escapeHTML(gain.name)}</p></${interactive?'button':'article'}>`}).join('')}
function metrics(){const data=progressData();let options=data.filter(m=>m.group===state.group);if(!options.length&&data.length){state.group=data[0].group;options=data.filter(m=>m.group===state.group)}const metric=options.find(m=>m.name===state.metricName)||options[0];if(metric)state.metricName=metric.name;return `${studentHeader()}<div class="page-head"><div><h1>Mirá todo lo que avanzaste.</h1><p>El progreso de ${escapeHTML(person().name)}, ejercicio a ejercicio.</p></div>${btn('Exportar progreso','progress-pdf','primary','download')}</div>${profileTabs('metrics')}<div class="progress-top spaced"><div>${periodControls()}<p class="period-label">${rangeLabel()}</p></div><button class="link-button" data-action="toggle-empty">${state.empty?'Volver a los registros':'Ver sin registros'}</button></div>${state.period==='custom'?`<div class="date-range"><label class="field"><span>Desde</span><input id="date-start" type="date" value="${state.customStart}"></label><label class="field"><span>Hasta</span><input id="date-end" type="date" value="${state.customEnd}"></label>${btn('Ver período','custom-dates')}</div>`:''}${data.length?`<div class="section-intro"><h2>Tu evolución por grupo muscular</h2><p>Explorá las cargas y cómo cambiaron durante este período.</p></div><div class="muscle-progress-grid">${muscleCards(data)}</div><section class="card spaced"><div class="card-head"><div><span class="eyebrow">${state.group.toUpperCase()}</span><h2 style="margin-top:9px">${escapeHTML(metric.name)}</h2></div><label class="field metric-picker"><span>Ver ejercicio</span><select id="metric-exercise">${options.map(m=>`<option ${m.name===metric.name?'selected':''}>${escapeHTML(m.name)}</option>`).join('')}</select></label></div><div class="progress-comparison"><div><span>Al inicio</span><strong>${metric.first} <small>kg</small></strong></div><span class="comparison-arrow">${icon('arrow')}</span><div><span>Último registro</span><strong>${metric.last} <small>kg</small></strong></div><span class="progress-gain">${deltaLabel(metric)}</span></div><div class="chart-area">${chart(metric)}</div><p class="chart-context">${metric.points.length} registros · ${metric.points.every(p=>p.reps===metric.points[0].reps)?`${metric.points[0].reps} repeticiones por registro`:'Repeticiones variables: compará el contexto de cada registro'} · ${metric.name.includes('mancuerna')?'Peso por mancuerna':'Carga externa registrada'}</p></section><p class="fineprint">Mostramos cambios de carga del mismo ejercicio. La mayor carga de un grupo no mide su fuerza absoluta ni permite comparar músculos o máquinas entre sí. Datos ficticios de demostración.</p>`:`<section class="card">${emptyState()}</section>`}`}
function paperHeader(){return `<div class="paper-brand"><div class="paper-logo"><img src="favicon.svg" alt="Logo provisional">MATEO TORRES</div><span class="eyebrow" style="font-size:8px">PERSONAL TRAINER</span></div>`}
function paperFooter(page,total){return `<div class="paper-foot"><span>${escapeHTML(person().name)} · ${dateLabel(TODAY)}<br>Datos de demostración</span><span>${page} / ${total}</span></div>`}
function paperExerciseTable(rows){return `<table class="paper-table"><thead><tr><th>EJERCICIO</th><th>SERIES</th><th>REPS</th><th>PESO</th></tr></thead><tbody>${rows.map(e=>`<tr><td>${escapeHTML(e.name)}</td><td>${e.sets??'—'}</td><td>${e.reps??'—'}</td><td>${e.weight??'—'} kg</td></tr>`).join('')||'<tr><td colspan="4">Sin ejercicios asignados</td></tr>'}</tbody></table>`}
function routinePaper(){const r=activeRoutine();if(!r)return emptyState();return r.weeks.map((days,w)=>`<article class="paper">${paperHeader()}<h2>RUTINA</h2><p class="paper-person">${escapeHTML(person().name)}</p><p class="paper-sub">Fecha: 23/09/2026 · ${escapeHTML(r.name)}<br>Inicio del ciclo: ${dateLabel(r.date)}</p><div class="paper-meta"><strong>SEMANA ${w+1} / 4</strong><span>${days.length} días · Rutina completa</span></div>${days.map((d,i)=>`<h3>Día ${i+1} · ${escapeHTML(d.title)} <span class="muted">/ ${d.weekday}</span></h3><p class="paper-section">ENTRADA EN CALOR · MOVILIDAD</p>${paperExerciseTable(d.mobility)}<p class="paper-section">APROXIMACIONES</p>${paperExerciseTable(d.approximation)}<p class="paper-section">PARTE PRINCIPAL</p>${paperExerciseTable(d.main)}`).join('')}${paperFooter(w+1,4)}</article>`).join('')}
function progressPaper(){const data=progressData();const groups=[...new Set(data.map(d=>d.group))];return `<article class="paper">${paperHeader()}<h2>TU PROGRESO</h2><p class="paper-person">${escapeHTML(person().name)}</p><p class="paper-sub">Fecha: 23/09/2026</p><div class="paper-meta"><strong>${rangeLabel()}</strong><span>${rangeInfo().label}</span></div>${data.length?`<h3>Así evolucionaron tus cargas</h3><div class="paper-muscles">${muscleCards(data,false)}</div><p class="fineprint">Mayor carga y evolución del ejercicio indicado para cada grupo. No se comparan fuerzas absolutas entre grupos.</p>`:emptyState()}${paperFooter(1,groups.length+1)}</article>${groups.map((group,i)=>`<article class="paper">${paperHeader()}<h2>${group}</h2><p class="paper-sub">${escapeHTML(person().name)} · ${rangeLabel()}</p>${data.filter(m=>m.group===group).map(m=>`<section class="paper-exercise"><h3>${escapeHTML(m.name)}</h3><div class="paper-meta"><span>${m.first} kg → <strong>${m.last} kg</strong></span><strong>${deltaLabel(m)}</strong></div>${chart(m)}<p class="paper-sub">${m.points.length} registros · ${m.points.every(p=>p.reps===m.points[0].reps)?m.points[0].reps+' repeticiones por registro':'Repeticiones variables'} · ${m.name.includes('mancuerna')?'Peso por mancuerna':'Carga externa'}</p></section>`).join('')}${paperFooter(i+2,groups.length+1)}</article>`).join('')}`}
function documents(){const progress=state.document==='progress';return `${studentHeader()}<div class="page-head"><div><h1>${progress?'Su progreso, en un documento.':'Su rutina, en un documento.'}</h1><p>${escapeHTML(person().name)} · ${progress?rangeLabel():'RUTINA · 23/09/2026'}</p></div>${btn('Exportar PDF','export-preview','primary','download')}</div><div class="document-layout document-layout-solo"><section class="paper-stage" aria-label="Documento completo">${progress?progressPaper():routinePaper()}</section></div>`}

const views={agenda,students,profile,editor,bank,metrics,documents};
