import {test,expect} from '@playwright/test';
import {accounts,createStudent,dropFixture,execute,command} from '../fixtures/cloud';
import {routineFixture} from '../fixtures/routine';
async function prepared(){const a=await createStudent();const doc=routineFixture(),draftId=crypto.randomUUID(),month=new Date().toISOString().slice(0,7);const save=await execute(a.client,command(a.workspaceId,a.studentId,'save_draft',{draftId,expectedDraftRevision:0,baseRoutineRevisionId:null,document:doc},a.revision));const pub=await execute(a.client,command(a.workspaceId,a.studentId,'publish_routine',{draftId,expectedDraftRevision:1,baseRoutineRevisionId:null,targetMonth:month},save.revision));const start=await execute(a.client,command(a.workspaceId,a.studentId,'start_session',{sessionId:crypto.randomUUID(),periodId:pub.patch.period.id,routineRevisionId:pub.patch.routine.id,dayId:doc.weeks[0][0].id,week:1,date:month+'-03',time:'18:00',timezone:'America/Argentina/Buenos_Aires'},pub.revision));return {...a,snapshot:start.patch};}
test('offline edits survive a reload and synchronize exactly once',async({page})=>{
 const a=await prepared();try{
  await page.goto('/login');await page.getByLabel('Email').fill(accounts[0].email);await page.getByLabel('Contraseña',{exact:true}).fill(accounts[0].password);await page.getByRole('button',{name:'Ingresar',exact:true}).click();await expect(page.getByRole('navigation')).toBeVisible();await page.goto('/entrenar/'+a.studentId);await expect(page.getByLabel('Peso kg')).toHaveValue('20');
  await page.route('http://127.0.0.1:54341/**',r=>r.abort());await page.getByLabel('Peso kg').fill('42,5');await page.getByLabel('Peso kg').blur();await expect(page.getByRole('status')).toContainText('pendiente de sincronizar');await page.reload();await expect(page.getByLabel('Peso kg')).toHaveValue('42.5');await expect(page.getByRole('status')).toContainText('pendiente de sincronizar');
  await page.unroute('http://127.0.0.1:54341/**');await page.getByRole('link',{name:'Ajustes',exact:true}).click();await page.getByRole('button',{name:'Reintentar sincronización'}).click();await page.goto('/entrenar/'+a.studentId);await expect(page.getByText('Sincronizado',{exact:true})).toBeVisible();const sets=await a.client.from('session_sets').select('weight').eq('student_id',a.studentId);expect(sets.data?.map(s=>s.weight)).toEqual([42.5,42.5]);const audit=await a.client.from('audit_events').select('id').eq('student_id',a.studentId).eq('kind','adjust_prescription');expect(audit.data).toHaveLength(1);
 }finally{await dropFixture(a.studentId);}
});
