import {useEffect,useRef,useState} from 'react';
import {Link,useParams} from 'react-router-dom';
import {liveQuery} from 'dexie';
import {Check,Timer,ChevronDown} from 'lucide-react';
import type {SessionItem,TrainingSession} from '@pulso/domain/contracts';
import {parseNumber,type NumericField as NumericName} from '@pulso/domain/numbers';
import {useData} from '../../app/DataProvider';
import {gateway} from '../../adapters/supabase-gateway';
export function TrainingScreen(){
 const{id}=useParams();const data=useData();const row=data.rows.find(r=>r.studentId===id),session=row?.projection.sessions[0];const queue=data.pending.filter(p=>p.studentId===id);
 const[error,setError]=useState(''),[finish,setFinish]=useState(false),[busy,setBusy]=useState(false),[empty,setEmpty]=useState(false),[rawCount,setRawCount]=useState(0);
 useEffect(()=>{const sub=liveQuery(()=>data.db.rawInputs.where('studentId').equals(id!).count()).subscribe(setRawCount);return()=>sub.unsubscribe();},[data.db,id]);
 if(!row)return <p>Cargando alumno…</p>;
 if(!session)return <><h1>Entrenamiento finalizado</h1><p>Los resultados confirmados ya están en el historial de {row.projection.student.name}.</p><div className="row"><Link className="button" to="/hoy">Volver a Hoy</Link><Link className="button secondary" to={'/historial/'+id}>Ver resultados</Link></div></>;
 const conflict=queue.find(p=>p.state==='conflict'||p.state==='rejected');const closing=queue.some(p=>p.command.kind==='finish_session');
 async function close(){setBusy(true);setError('');try{if(await data.db.rawInputs.where('studentId').equals(id!).count())throw Error('Hay campos sin confirmar. Corregilos antes de finalizar.');const current=await data.db.read(id!);await data.db.stage(data.makeCommand(id!,'finish_session',{sessionId:session!.id,quickConfirmItemIds:session!.items.filter(i=>!i.skipped).map(i=>i.id),allowEmpty:empty},current!.confirmed.revision));setFinish(false);void data.sync();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <><div className="active-strip" aria-label="Alumnos entrenando">{data.rows.filter(r=>r.projection.sessions.length).map(r=><Link key={r.studentId} className={'active-chip '+(r.studentId===id?'selected':'')} to={'/entrenar/'+r.studentId}>{r.projection.student.name}<span>{data.pending.some(p=>p.studentId===r.studentId)?' · pendiente':''}</span></Link>)}</div><header className="training-header"><div><p className="eyebrow">ENTRENAMIENTO EN CURSO · SEMANA {session.week}</p><h1>{row.projection.student.name}</h1><p className="muted">{row.projection.routine?.document.name}</p></div><span className={'save-indicator '+(queue.length||rawCount?'pending':'')} role="status">{conflict?'Revisar cambio':rawCount?'Campo pendiente de confirmar':closing?'Finalización pendiente':queue.length?'Guardado en este dispositivo · pendiente de sincronizar':'Sincronizado'}</span></header>
 {error&&<p className="error" role="alert">{error}</p>}{conflict&&<div className="error"><h2>Este alumno necesita una revisión</h2><p>{conflict.error}</p><Link to="/ajustes">Abrir centro de sincronización</Link></div>}{closing&&<div className="notice">El cierre está guardado en este dispositivo. Esperando confirmación del servidor.</div>}
 <p className="scope-note">Los ajustes rápidos se aplican a esta sesión y a las semanas siguientes. Las series ya registradas conservan sus valores.</p><RestTimer session={session}/>
 <div className="stack">{[...new Set(session.items.map(i=>i.block_id))].map(blockId=>{const items=session.items.filter(i=>i.block_id===blockId);return <details className="training-block" open key={blockId}><summary><span>{items[0].block_name}</span><small>{items.length} ejercicios · Macro: {items[0].macro_rest??'—'} s entre {items[0].macro_target==='series'?'series':'bloques'}</small><ChevronDown size={18}/></summary><div className="stack">{items.map(item=><ExerciseRow key={item.id} item={item} session={session} studentId={id!} disabled={closing||!!conflict} onError={setError}/>)}</div></details>;})}</div><div className="finish-bar"><span>{session.items.filter(i=>i.skipped).length} omitidos · {session.items.length} ejercicios</span><button className="button" disabled={closing||!!conflict} onClick={()=>setFinish(true)}>Finalizar entrenamiento</button></div>
 {finish&&<div className="modal-backdrop"><section className="card modal stack" role="dialog" aria-modal="true" aria-label="Finalizar entrenamiento"><h2>Todo lo de hoy, registrado</h2><p>{session.items.flatMap(i=>i.sets).filter(s=>s.state==='done').length} series registradas individualmente. Los ejercicios pendientes se confirmarán con sus valores actuales y quedarán identificados como confirmación rápida.</p><label className="row"><input type="checkbox" checked={empty} onChange={e=>setEmpty(e.target.checked)}/>Permitir cierre sin ejercicios realizados</label>{error&&<p className="error" role="alert">{error}</p>}<button className="button" disabled={busy||rawCount>0} onClick={close}>Confirmar cierre</button><button className="button secondary" onClick={()=>setFinish(false)}>Seguir entrenando</button></section></div>}</>;
}
function ExerciseRow({item,session,studentId,disabled,onError}:{item:SessionItem;session:TrainingSession;studentId:string;disabled:boolean;onError:(s:string)=>void}){
 const data=useData();const[detail,setDetail]=useState(false);
 async function stage(kind:'skip_item'|'record_set',payload:Record<string,unknown>){try{const row=await data.db.read(studentId);await data.db.stage(data.makeCommand(studentId,kind,{sessionId:session.id,itemId:item.id,...payload},row!.confirmed.revision));void data.sync();}catch(e){onError((e as Error).message);}}
 return <article className={'card training-exercise '+(item.skipped?'skipped':'')}><div className="row spread"><div><p className="eyebrow">{item.group}{item.warmup?' · aproximación':''}</p><h2>{item.name}</h2><PreviousResult exerciseId={item.exercise_id} studentId={studentId}/></div><label className="row"><input type="checkbox" checked={item.skipped} disabled={disabled} onChange={e=>void stage('skip_item',{skipped:e.target.checked})}/>No se realizó</label></div><div className="live-fields">{(['sets',...(item.type==='time'?['durationSec']:item.type==='load_reps'?['weight','reps']:['reps']),'microRest'] as NumericName[]).map(field=><LiveInput key={field} field={field} label={{weight:'Peso kg',sets:'Series',reps:'Repeticiones',durationSec:'Duración (s)',microRest:'Descanso micro (s)',macroRest:'Descanso macro (s)'}[field]} value={field==='macroRest'?item.macro_rest:item.prescription[field]} item={item} session={session} studentId={studentId} disabled={disabled||item.skipped} onError={onError}/>)}</div><button className="link-button" onClick={()=>setDetail(!detail)}>{detail?'Ocultar':'Detalle de series'} · {item.sets.filter(s=>s.state==='done').length}/{item.sets.length}</button>{detail&&<div className="set-list"><p className="muted">Registrar una serie conserva su ejecución. Para cambiarla después usá la corrección con motivo del historial.</p>{item.sets.map(set=><SetEditor key={set.id} set={set} type={item.type} disabled={disabled||item.skipped} onSave={payload=>stage('record_set',{setId:set.id,ordinal:set.ordinal,...payload})}/>)}</div>}</article>;
}
function SetEditor({set,type,disabled,onSave}:{set:SessionItem['sets'][number];type:SessionItem['type'];disabled:boolean;onSave:(p:Record<string,unknown>)=>Promise<void>}){
 const[weight,setWeight]=useState(String(set.weight??'')),[reps,setReps]=useState(String(set.reps??'')),[duration,setDuration]=useState(String(set.duration_sec??'')),[error,setError]=useState('');
 useEffect(()=>{if(set.state==='pending'){setWeight(String(set.weight??''));setReps(String(set.reps??''));setDuration(String(set.duration_sec??''));}},[set.weight,set.reps,set.duration_sec,set.state]);
 if(set.state!=='pending')return <div className="set-row"><strong>Serie {set.ordinal}</strong><span>{set.weight!==null?set.weight+' kg · ':''}{type==='time'?set.duration_sec+' s':set.reps+' reps'}</span><span className="badge">{set.state==='done'?'Registrada':'Omitida'}</span></div>;
 async function save(state:'done'|'skipped'){const w=parseNumber('weight',weight),r=parseNumber('reps',reps),d=parseNumber('durationSec',duration);if((type==='load_reps'&&!w.ok)||(type!=='time'&&!r.ok)||(type==='time'&&!d.ok)){setError('Completá valores válidos.');return;}setError('');await onSave({state,weight:w.ok?w.value:null,reps:r.ok?r.value:null,durationSec:d.ok?d.value:null});}
 return <div className="set-row"><strong>Serie {set.ordinal}</strong>{type==='load_reps'&&<input aria-label={'Peso serie '+set.ordinal} inputMode="decimal" value={weight} onChange={e=>setWeight(e.target.value)}/>}<input aria-label={(type==='time'?'Segundos':'Reps')+' serie '+set.ordinal} inputMode="numeric" value={type==='time'?duration:reps} onChange={e=>type==='time'?setDuration(e.target.value):setReps(e.target.value)}/><button className="button small" aria-label={'Registrar serie '+set.ordinal} disabled={disabled} onClick={()=>void save('done')}><Check size={16}/></button><button className="link-button" disabled={disabled} onClick={()=>void save('skipped')}>Omitir</button>{error&&<span role="alert">{error}</span>}</div>;
}
function LiveInput({field,label,value,item,session,studentId,disabled,onError}:{field:NumericName;label:string;value:number|null;item:SessionItem;session:TrainingSession;studentId:string;disabled:boolean;onError:(s:string)=>void}){
 const data=useData(),[raw,setRaw]=useState(value===null?'':String(value)),[state,setState]=useState('');const timer=useRef<ReturnType<typeof setTimeout>|null>(null),focused=useRef(false),latest=useRef(raw),write=useRef<Promise<unknown>>(Promise.resolve()),active=useRef(true);const rawId=session.id+':'+item.id+':'+field;
 useEffect(()=>{active.current=true;void data.db.rawInputs.get(rawId).then(saved=>{if(saved&&active.current){setRaw(saved.raw);latest.current=saved.raw;setState('Pendiente de confirmar');}});return()=>{active.current=false;if(timer.current)clearTimeout(timer.current);};},[rawId,data.db]);
 useEffect(()=>{if(!focused.current&&!state){const text=value===null?'':String(value);setRaw(text);latest.current=text;}},[value]);
 async function commit(text:string){await write.current;const result=parseNumber(field,text);if(!result.ok){setState('Revisá el valor');return;}try{const row=await data.db.read(studentId);const saved=await data.db.rawInputs.get(rawId);if(!saved||saved.raw!==text)return;await data.db.stage(data.makeCommand(studentId,'adjust_prescription',{sessionId:session.id,itemId:item.id,field,value:result.value,scope:'session_and_future'},saved.revision),rawId);if(active.current)setState('');void data.sync();}catch(e){if(active.current)setState('No confirmado');onError((e as Error).message);}}
 function change(text:string){setRaw(text);latest.current=text;setState('Guardando en este dispositivo');if(timer.current)clearTimeout(timer.current);
  write.current=write.current.then(async()=>{const row=await data.db.read(studentId);await data.db.rawInputs.put({id:rawId,studentId,sessionId:session.id,itemId:item.id,field,raw:text,revision:row!.confirmed.revision});if(active.current&&latest.current===text)setState('Guardado local');}).catch(()=>{if(active.current)setState('No se pudo guardar');onError('No se pudo guardar este campo en el dispositivo. Conservá el valor y reintentá.');});
  timer.current=setTimeout(()=>void commit(text),300);
 }
 return <label className="field">{label}<input inputMode={field==='weight'?'decimal':'numeric'} value={raw} disabled={disabled} onFocus={e=>{focused.current=true;e.target.select();}} onChange={e=>change(e.target.value)} onBlur={()=>{focused.current=false;if(timer.current)clearTimeout(timer.current);void commit(latest.current);}} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();}}/><small className="field-hint">{state}</small></label>;
}
function PreviousResult({exerciseId,studentId}:{exerciseId:string;studentId:string}){const[value,setValue]=useState('Sin registro anterior');useEffect(()=>{let active=true;import('../../adapters/supabase').then(async({cloud})=>{const{data,error}=await cloud().from('session_items').select('id,session_sets(weight,reps,duration_sec,state),sessions!inner(status,started_at)').eq('student_id',studentId).eq('exercise_id',exerciseId).eq('sessions.status','closed').order('id').limit(20);if(!active||error)return;const rows=(data??[]).sort((a,b)=>String((b.sessions as unknown as {started_at:string}).started_at).localeCompare(String((a.sessions as unknown as {started_at:string}).started_at)));const set=rows[0]?.session_sets.find(s=>s.state==='done');if(set)setValue('Anterior: '+(set.weight!==null?set.weight+' kg · ':'')+(set.reps!==null?set.reps+' reps':set.duration_sec+' s'));});return()=>{active=false;};},[exerciseId,studentId]);return <small>{value}</small>;}
function RestTimer({session}:{session:TrainingSession}){const{db}=useData();const[end,setEnd]=useState<number|null>(null),[paused,setPaused]=useState<number|null>(null),[now,setNow]=useState(Date.now());
 useEffect(()=>{let active=true;void db.meta.get('timer:'+session.id).then(r=>{if(r&&active){const t=r.value as {end:number|null;paused:number|null};setEnd(t.end);setPaused(t.paused);}});const timer=setInterval(()=>setNow(Date.now()),500);return()=>{active=false;clearInterval(timer);};},[session.id,db]);
 const remaining=paused??Math.max(0,Math.ceil(((end??now)-now)/1000));function save(nextEnd:number|null,nextPaused:number|null){setEnd(nextEnd);setPaused(nextPaused);void db.meta.put({key:'timer:'+session.id,value:{end:nextEnd,paused:nextPaused}});}
 return <div className="rest-timer row spread"><div className="row"><Timer size={18}/><strong>Descanso · {Math.floor(remaining/60)}:{String(remaining%60).padStart(2,'0')}</strong></div><div className="row"><button className="link-button" onClick={()=>save(Date.now()+60_000,null)}>60 s</button><button className="link-button" onClick={()=>save(Date.now()+(remaining+15)*1000,null)}>+15 s</button><button className="link-button" onClick={()=>paused!==null?save(Date.now()+paused*1000,null):save(null,remaining)}>{paused!==null?'Continuar':'Pausar'}</button></div></div>;
}
