const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const read=name=>fs.readFileSync(path.resolve(__dirname,'..',name),'utf8');
async function session(saved){
 const context={structuredClone,console,Date,setTimeout,clearTimeout,failStorage:false,document:{addEventListener(){},querySelectorAll:()=>[],querySelector:()=>null},sessionStorage:{getItem:()=>null,setItem(){}},localStorage:{getItem:()=>null}};
 context.window=context;context.window.addEventListener=()=>{};vm.createContext(context);
 for(const file of ['data.js','training-schema.js','training-domain.js','training-months.js','training-controller.js','training-backup.js','model.js','ui-core.js','views.js','anatomy.js','calendar.js','experience.js','history.js','training-views.js'])vm.runInContext(read(file),context);
 vm.runInContext(read('app.js').split("document.addEventListener('click'")[0],context);
 vm.runInContext(read('training-editor.js'),context);
 vm.runInContext(read('training-app.js').replace(/bootTraining\(\);\s*$/,''),context);
 context.initial=saved?JSON.parse(saved):null;
 vm.runInContext(`let disk=initial||TrainingSchema.migrateV5({version:5,db:copy(DB),serial});
 hydrateTraining(disk,false);
 trainingRepo={load:async()=>copy(disk),transact:async({expectedRevision,operationId},reduce)=>{if(failStorage)throw Object.assign(Error('No se pudo guardar'),{code:'WRITE_FAILED'});if(disk.revision!==expectedRevision)throw Object.assign(Error('Conflict'),{code:'CONFLICT'});const next=reduce(copy(disk));next.revision=disk.revision+1;next.operationIds=[...disk.operationIds,operationId];TrainingSchema.validate(next);disk=copy(next);return copy(disk)}};
 trainingController=TrainingController.create({repo:trainingRepo,snapshot:disk,context:trainingContext,onState:update=>{if(update.snapshot.revision!==trainingHydratedRevision)hydrateTraining(update.snapshot)}});trainingReady=true;
 let lastModal,lastToast;modal=(...args)=>{lastModal=args};render=()=>{};closeModal=()=>{};go=()=>{};toast=text=>{lastToast=text};error=text=>{lastToast=text};`,context);
 return {get:code=>vm.runInContext(code,context),run:code=>vm.runInContext(`(async()=>{${code}})()`,context),saved:()=>vm.runInContext('JSON.stringify(disk)',context),context};
}
const main='blocks.find(b=>b.type==="main").exercises';
test('new draft stays unsaved across navigation and reload',async()=>{const s=await session();await s.run(`assignRoutine(person().routine);mutateDays(d=>d.${main}[0].weight=99);await action('close')`);assert.equal(s.get('draftHasChanges(person())'),true);assert.equal((await session(s.saved())).get('Boolean(person().draft)'),false);assert.match(s.get('editorScreen()'),/Guardar borrador/)});
test('manual save persists and further draft edits cannot leak',async()=>{const s=await session();await s.run(`assignRoutine(person().routine);mutateDays(d=>d.${main}[0].weight=41);await action('save-draft');mutateDays(d=>d.${main}[0].weight=72);await action('close')`);assert.equal((await session(s.saved())).get(`person().draft.weeks[0][0].${main}[0].weight`),41)});
test('saving one student does not save another pending draft',async()=>{const s=await session();await s.run("assignRoutine(person().routine);state.person=1;assignRoutine(person().routine);await action('save-draft')");const r=await session(s.saved());assert.equal(r.get('Boolean(DB.people[0].draft)'),false);assert.equal(r.get('Boolean(DB.people[1].draft)'),true)});
test('failed save retains pending edits and last confirmed version',async()=>{const s=await session();await s.run("assignRoutine(person().routine);await action('save-draft')");const before=s.saved();await s.run(`mutateDays(d=>d.${main}[0].weight=88);failStorage=true;await action('save-draft')`);assert.equal(s.saved(),before);assert.equal(s.get('draftHasChanges(person())'),true);assert.match(s.get('editorScreen()'),/No se pudo guardar/);await s.run("failStorage=false;await trainingController.reloadConflict();await action('save-draft')");assert.equal((await session(s.saved())).get(`person().draft.weeks[0][0].${main}[0].weight`),88)});
test('activation needs saved changes and archives current independently',async()=>{const s=await session();const id=s.get('person().routine.id');await s.run("assignRoutine(person().routine);await action('activate-draft')");assert.equal(s.get('lastModal[0]'),'Guardá el borrador primero');await s.run("await action('save-draft');await action('activate-draft');await action('confirm-activate')");const r=await session(s.saved());assert.equal(r.get('Boolean(person().draft)'),false);assert.equal(r.get('person().archives[0].id'),id);assert.notEqual(r.get('person().routine.id'),id)});
test('discard removes saved and working draft without changing current',async()=>{const s=await session();const before=s.get('JSON.stringify(person().routine)');await s.run("assignRoutine(person().routine);await action('save-draft');await action('confirm-discard')");const r=await session(s.saved());assert.equal(r.get('Boolean(person().draft)'),false);assert.equal(r.get('JSON.stringify(person().routine)'),before)});
test('new templates and inserted exercises have undefined prescription',async()=>{const s=await session();await s.run("const t=emptyTemplate('Nueva',2);DB.templates.push(t);state.templateId=t.id;state.week=1;state.day=0;addExercise(DB.library[0].id,'main')");assert.equal(s.get(`currentDay().${main}[0].weight`),null);assert.equal(s.get('activeRoutine().weeks.length'),4);assert.doesNotMatch(s.get('routineBlockView(currentDay().blocks[2])'),/>null</)});
test('incomplete draft cannot activate or preview document',async()=>{const s=await session();await s.run("assignRoutine(person().routine);addExercise(DB.library[0].id,'main');await action('save-draft');await action('activate-draft')");assert.equal(s.get('lastModal[0]'),'Completá el borrador');assert.doesNotMatch(s.get('editorScreen()'),/Ver documento/)});
test('saved draft audit captures weight changes only on manual save',async()=>{const s=await session();await s.run(`assignRoutine(person().routine);await action('save-draft');mutateDays(d=>d.${main}[0].weight=65);await action('save-draft')`);assert.match(s.get('JSON.stringify(person().history.at(-1).details)'),/65 kg/);assert.match((await session(s.saved())).get('JSON.stringify(person().history.at(-1).details)'),/65 kg/)});
test('legacy session correction retains audit and corrected progress',async()=>{const s=await session();await s.run("const r={date:TODAY,name:'Prueba',group:'Espalda',weight:20,sets:3,reps:8,exerciseId:'test',routineId:person().routine.id,zone:'main',source:'legacy'};await saveSession(person(),[r]);await saveSession(person(),[{...r,weight:25}])");assert.equal(s.get('person().history.at(-1).corrections[0].before.weight'),20);assert.equal(s.get("progressData().find(e=>e.name==='Prueba').last"),25)});
test('invalid legacy result or storage failure does not alter history',async()=>{const s=await session();const before=s.get('JSON.stringify(person().records)');await s.run("const r={date:TODAY,name:'Prueba',group:'Espalda',weight:null,sets:3,reps:8};if(await saveSession(person(),[r]))throw Error('Invalid saved');failStorage=true;if(await saveSession(person(),[{...r,weight:20}]))throw Error('Failure saved')");assert.equal(s.get('JSON.stringify(person().records)'),before)});
test('existing archives and records remain visible without invented audit',async()=>{const s=await session();assert.equal(s.get("historyEntries(person()).filter(e=>e.kind==='routine').length"),3);assert.equal(s.get('person().history.length'),0);assert.match(s.get('exerciseBank()'),/Banco de ejercicios/)});
test('catalog creation persists and duplicate names are rejected',async()=>{const s=await session();await s.run("const fields={'#exercise-name':{value:'Prueba nueva'},'#exercise-group':{value:'Espalda'},'#exercise-notes':{value:'Descripción'}};document.querySelector=key=>fields[key];await action('save-new-exercise');await action('save-new-exercise')");assert.equal(s.get("DB.library.filter(e=>e.name==='Prueba nueva').length"),1);assert.equal((await session(s.saved())).get('DB.library.at(-1).name'),'Prueba nueva')});
test('new template is blank and saved independently',async()=>{const s=await session();await s.run("const fields={'#template-name':{value:'Desde cero'},'#template-days':{value:'3'}};document.querySelector=key=>fields[key];await action('save-empty-template')");assert.equal(s.get('activeRoutine().weeks.every(w=>w.length===3&&w.every(d=>d.blocks.every(b=>!b.exercises.length)))'),true);assert.equal((await session(s.saved())).get('DB.templates.at(-1).name'),'Desde cero')});
test('progress document is not interactive and ignores selected muscle',async()=>{const s=await session();const a=s.get("state.group='Hombros';bodyMap(progressData(),false)"),b=s.get("state.group='Pecho';bodyMap(progressData(),false)");assert.equal(a,b);assert.doesNotMatch(a,/data-body-group|tabindex|role="button"/)});
test('anatomical figures contain supported muscle groups',async()=>{const s=await session();for(const gender of ['masculino','femenino']){await s.run(`person().gender='${gender}'`);const groups=JSON.parse(s.get('JSON.stringify(MUSCLE_GROUPS)'));const map=s.get('bodyMap(progressData())');for(const group of groups)assert.ok(map.includes(`data-body-group="${group}"`))}});
test('muscles without data remain selected with honest empty state',async()=>{const s=await session();await s.run("state.group='Antebrazos'");assert.equal(s.get('metricSelection(progressData()).selected'),undefined);assert.match(s.get('progressScreen()'),/Sin datos en este período/)});
test('muscle aliases map correctly',async()=>{const s=await session();await s.run("globalThis.alias=[{...progressData()[0],group:'Gemelos'}];state.group='Pantorrillas';state.bodyMode='load'");assert.equal(s.get('groupMetrics(alias)[0].group'),'Pantorrillas');assert.equal(s.get('metricSelection(alias).group.length'),1)});
test('saving draft concurrently with a live adjustment cannot overwrite session or audit',async()=>{
 const s=await session();await s.run(`assignRoutine(person().routine);await saveDraft(person());await trainingController.execute({type:'start',personId:person().id,sessionId:'concurrent',dayId:person().routine.weeks[0][0].id,week:1,date:TODAY,time:'10:00'});mutateDays(d=>d.title='Nuevo título');const b=person().routine.weeks[0][0].blocks.find(b=>b.type==='main');const live=trainingController.execute({type:'edit',sessionId:'concurrent',blockId:b.id,exerciseId:b.exercises[0].id,field:'weight',value:99});const draft=saveDraft(person());await Promise.all([live,draft]);`);
 const r=await session(s.saved());assert.equal(r.get("DB.sessions[0].blocks.find(b=>b.type==='main').exercises[0].weight"),99);assert.equal(r.get("person().history.filter(e=>e.field==='weight'&&e.after===99).length"),1);
});
test('saving a draft never persists another unsaved template',async()=>{
 const s=await session();const before=s.get(`DB.templates[0].weeks[0][0].${main}[0].weight`);await s.run(`DB.templates[0].weeks[0][0].${main}[0].weight=111;assignRoutine(person().routine);await saveDraft(person())`);
 assert.equal((await session(s.saved())).get(`DB.templates[0].weeks[0][0].${main}[0].weight`),before);
});
test('confirming start after midnight refreshes date and renews month',async()=>{
 const s=await session();await s.run(`const NativeDate=Date;const nextDay=new NativeDate(2026,9,1,0,1).getTime();Date=class extends NativeDate{constructor(...args){super(...(args.length?args:[nextDay]))}};TODAY='2026-09-30';modalContext={trainingPerson:person().id};const day=person().routine.weeks[0][0].id;document.querySelector=key=>({'#training-day':{value:day},'#training-week':{value:'1'},'#training-time':{value:'00:01'}}[key]);openTraining=()=>{};await trainingAction('train-start-confirm');`);
 assert.equal(s.get('DB.sessions[0].date'),'2026-10-01');assert.equal(s.get('DB.sessions[0].period'),'2026-10');assert.equal(s.get('person().routine.period'),'2026-10');
});
test('same-day session results display newest first',async()=>{
 const s=await session();await s.run(`const p=person();for(const [id,hour] of [['early',10],['late',11]]){trainingContext.now=()=>new Date(TODAY+'T'+hour+':00:00');await trainingController.execute({type:'start',personId:p.id,sessionId:id,dayId:p.routine.weeks[0][0].id,week:1,date:TODAY,time:hour+':00'});await trainingController.execute({type:'finish',sessionId:id})}`);
 assert.equal(s.get("historyEntries(person()).filter(e=>e.kind==='sessions'&&e.records[0].sessionId)[0].id"),'late');
});
test('navigation context restores the selected student and saved draft after hydration',async()=>{
 const s=await session();await s.run("state.person=5;assignRoutine(person().routine);await saveDraft(person());const v={personId:person().id,draftMode:true,week:3,day:0};sessionStorage.getItem=key=>key==='pulso-view-v5'?JSON.stringify(v):null;state.person=0;state.draftMode=false;restoreTrainingContext()");assert.equal(s.get('state.person'),5);assert.equal(s.get('state.draftMode'),true);assert.equal(s.get('state.week'),3);
});
