const {test}=require('node:test'),assert=require('node:assert/strict');
const {load}=require('./helpers/load-training.cjs'),{fixture}=require('./helpers/training-fixture.cjs');
function setup(){const c=load(['training-schema.js','training-domain.js','training-controller.js']);let n=0;const context={id:()=>`op-${++n}`,now:()=>new Date(2026,8,28,10)};
 let disk=c.TrainingDomain.apply(fixture(),{type:'start',personId:'p1',sessionId:'s1',dayId:'d1',week:2,date:'2026-09-28',time:'10:00'},context),fail=false,delay=null;
 const repo={load:async()=>structuredClone(disk),transact:async({expectedRevision,operationId},reduce)=>{if(delay)await delay;if(fail)throw Object.assign(new Error('Write failed'),{code:'WRITE_FAILED'});if(disk.revision!==expectedRevision)throw Object.assign(new Error('Conflict'),{code:'CONFLICT'});const next=reduce(structuredClone(disk));next.revision++;next.operationIds.push(operationId);c.TrainingSchema.validate(next);disk=next;return structuredClone(disk)}};
 return {controller:c.TrainingController.create({repo,snapshot:disk,context,onState:()=>{}}),disk:()=>disk,setFail:v=>fail=v,setDelay:v=>delay=v,conflict:()=>disk.revision++};}
const field=raw=>({sessionId:'s1',blockId:'b1',exerciseId:'e1',field:'weight',raw});
test('failed autosave preserves pending input and retry writes it once',async()=>{const t=setup();t.setFail(true);t.controller.stage(field('22'));await assert.rejects(t.controller.flush());assert.equal(t.disk().db.sessions[0].blocks[0].exercises[0].weight,20);assert.equal(t.controller.pending().length,1);assert.equal(t.controller.status().state,'error');t.setFail(false);await t.controller.retry();assert.equal(t.disk().db.sessions[0].blocks[0].exercises[0].weight,22);assert.equal(t.controller.pending().length,0)});
test('new input during commit is not erased by the earlier completion',async()=>{const t=setup();let done;t.setDelay(new Promise(r=>done=r));t.controller.stage(field('22'));const pending=t.controller.flush();await new Promise(r=>setImmediate(r));t.controller.stage(field('24'));assert.equal(t.controller.snapshot().db.sessions[0].blocks[0].exercises[0].weight,20);done();await pending;t.setDelay(null);await t.controller.flush();assert.equal(t.disk().db.sessions[0].blocks[0].exercises[0].weight,24);assert.equal(t.controller.pending().length,0)});
test('invalid transient input blocks finalize and cannot become zero',async()=>{const t=setup();t.controller.stage(field(''));await assert.rejects(t.controller.flush());assert.equal(t.disk().db.sessions[0].blocks[0].exercises[0].weight,20);t.controller.stage(field('0'));await t.controller.flush();assert.equal(t.disk().db.sessions[0].blocks[0].exercises[0].weight,0)});
test('conflict retains pending edits and reload permits explicit reapply',async()=>{const t=setup();t.controller.stage(field('24'));t.conflict();await assert.rejects(t.controller.flush());assert.equal(t.controller.status().state,'conflict');assert.equal(t.controller.pending().length,1);await t.controller.reloadConflict();await t.controller.retry();assert.equal(t.disk().db.sessions[0].blocks[0].exercises[0].weight,24)});
