import {useState} from 'react';
import {Link,useNavigate} from 'react-router-dom';
import {Plus,ArrowRight,CalendarDays} from 'lucide-react';
import {useData} from '../../app/DataProvider';
import {todayKey,currentTime} from '@pulso/domain/dates';
export function Today(){
 const{rows,pending,error,db,onlineCommand,makeCommand,sync}=useData();const navigate=useNavigate();const[adding,setAdding]=useState(false),[studentId,setStudentId]=useState(''),[week,setWeek]=useState(Math.min(4,Math.ceil(Number(todayKey().slice(-2))/7))),[dayId,setDayId]=useState(''),[visitId,setVisitId]=useState<string|undefined>(),[failure,setFailure]=useState(''),[busy,setBusy]=useState(false),[date,setDate]=useState(todayKey());
 const active=rows.flatMap(r=>r.projection.sessions.map(s=>({student:r.projection.student,session:s})));const selected=rows.find(r=>r.studentId===studentId)?.projection;
 const visits=rows.flatMap(r=>r.projection.visits.filter(v=>v.date===date).map(v=>({...v,student:r.projection.student}))).sort((a,b)=>a.time.localeCompare(b.time));
 async function start(){setBusy(true);setFailure('');try{let snapshot=rows.find(r=>r.studentId===studentId)!.projection;
  if(snapshot.period?.month!==todayKey().slice(0,7)){snapshot=await onlineCommand(studentId,'ensure_period',{requestedMonth:todayKey().slice(0,7)},snapshot.revision);}
  if(!snapshot.routine||!snapshot.period)throw Error('Prepará y activá una rutina para este alumno.');
  const day=snapshot.routine.document.weeks[week-1].find(d=>d.id===dayId)??snapshot.routine.document.weeks[week-1][0];
  const sessionId=crypto.randomUUID();const command=makeCommand(studentId,'start_session',{sessionId,visitId,periodId:snapshot.period.id,routineRevisionId:snapshot.routine.id,dayId:day.id,week,date:todayKey(),time:currentTime(),timezone:'America/Argentina/Buenos_Aires'},snapshot.revision);
  await db.stage(command);void sync();navigate('/entrenar/'+studentId);
 }catch(e){setFailure((e as Error).message);}finally{setBusy(false);}}
 async function absence(studentId:string,id:string){setFailure('');try{const row=rows.find(r=>r.studentId===studentId)!;await onlineCommand(studentId,'mark_absent',{visitId:id},row.confirmed.revision);}catch(e){setFailure((e as Error).message);}}
 const[reschedule,setReschedule]=useState<{studentId:string;visitId:string}|null>(null),[newDate,setNewDate]=useState(todayKey()),[newTime,setNewTime]=useState('18:00');
 return <><header className="page-heading"><div><p className="eyebrow">{new Intl.DateTimeFormat('es-AR',{weekday:'long',day:'numeric',month:'long'}).format(new Date(date+'T12:00:00'))}</p><h1>Hoy, con vos.</h1><p className="muted">Tu atención en las personas. Cada avance, registrado.</p></div><button className="button" onClick={()=>{setAdding(true);setVisitId(undefined);}}><Plus size={18}/>Agregar ahora</button></header>{error&&<p className="notice">{error}</p>}{failure&&<p role="alert" className="error">{failure}</p>}
 <section><div className="row spread section-heading"><h2>Entrenando ahora <span className="count">{active.length}</span></h2><small>{pending.length?`${pending.length} cambios por confirmar`:'Tu espacio de seguimiento'}</small></div>{active.length?<div className="grid">{active.map(({student,session})=><Link className="card active-card student-card" key={session.id} to={'/entrenar/'+student.id}><div className="row"><div className="avatar">{student.name.slice(0,2).toUpperCase()}</div><div><h3>{student.name}</h3><small>{session.items.filter(i=>i.sets.some(s=>s.state==='done')).length} de {session.items.length} ejercicios con registro</small></div></div><div className="row spread"><span className="badge">En curso</span><ArrowRight size={18}/></div></Link>)}</div>:<div className="card empty"><CalendarDays size={32}/><h2>Listo para acompañar</h2><p>Iniciá desde la agenda o agregá a quien acaba de llegar.</p></div>}</section>
 <section className="agenda-section"><div className="row spread section-heading"><h2>Agenda del día</h2><label className="field"><span className="sr-only">Fecha de agenda</span><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label></div><div className="card agenda-list">{visits.map(v=><div className="agenda-row" key={v.id}><span className="time">{v.time.slice(0,5)}</span><div className="avatar">{v.student.name.slice(0,2).toUpperCase()}</div><div className="agenda-person"><strong>{v.student.name}</strong><small>{({pending:'Pendiente',open:'Entrenando',closed:'Finalizado',absent:'No asistió',rescheduled:'Reprogramado',cancelled:'Cancelado'})[v.status]}</small></div>{v.status==='pending'&&<div className="row"><button className="button small" disabled={date!==todayKey()} onClick={()=>{setStudentId(v.student.id);setVisitId(v.id);setAdding(true);}}>Iniciar</button><button className="link-button" onClick={()=>void absence(v.student.id,v.id)}>No asistió</button><button className="link-button" onClick={()=>setReschedule({studentId:v.student.id,visitId:v.id})}>Reprogramar</button></div>}</div>)}{!visits.length&&<div className="empty">No hay visitas programadas para este día.<br/><Link to="/alumnos">Organizar horarios de alumnos</Link></div>}</div></section>
 {adding&&<div className="modal-backdrop"><section className="card modal stack" role="dialog" aria-modal="true" aria-label="Agregar entrenamiento"><div className="row spread"><h2>Empezar ahora</h2><button className="link-button" onClick={()=>setAdding(false)}>Cerrar</button></div><label className="field">Alumno<select aria-label="Alumno" value={studentId} onChange={e=>{setStudentId(e.target.value);setDayId('');setVisitId(undefined);}}><option value="">Elegí un alumno</option>{rows.filter(r=>!r.projection.student.archived&&!r.projection.sessions.length).map(r=><option key={r.studentId} value={r.studentId}>{r.projection.student.name}</option>)}</select></label><label className="field">Semana<select value={week} onChange={e=>{setWeek(Number(e.target.value));setDayId('');}}>{[1,2,3,4].map(w=><option key={w}>{w}</option>)}</select></label><label className="field">Día de rutina<select value={dayId||selected?.routine?.document.weeks[week-1][0]?.id||''} onChange={e=>setDayId(e.target.value)}>{selected?.routine?.document.weeks[week-1].map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label>{studentId&&!selected?.routine&&<p className="notice">Este alumno necesita una <Link to={'/rutinas/'+studentId}>rutina activa</Link>.</p>}{failure&&<p role="alert" className="error">{failure}</p>}<button className="button" disabled={busy||!studentId||!selected?.routine} onClick={start}>Iniciar entrenamiento</button><small>Hora actual {currentTime()}. Esta llegada no cambia el horario semanal.</small></section></div>}
 {reschedule&&<div className="modal-backdrop"><section className="card modal stack"><h2>Reprogramar visita</h2><label className="field">Nueva fecha<input type="date" value={newDate} onChange={e=>setNewDate(e.target.value)}/></label><label className="field">Nueva hora<input type="time" value={newTime} onChange={e=>setNewTime(e.target.value)}/></label><button className="button" onClick={async()=>{try{const row=rows.find(r=>r.studentId===reschedule.studentId)!;await onlineCommand(row.studentId,'reschedule_visit',{visitId:reschedule.visitId,newVisitId:crypto.randomUUID(),date:newDate,time:newTime},row.confirmed.revision);setReschedule(null);}catch(e){setFailure((e as Error).message);}}}>Guardar nueva visita</button><button className="link-button" onClick={()=>setReschedule(null)}>Cancelar</button></section></div>}</>;
}
